### ISSUE TITLE
Discover return types from DocBlocks

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#10]
Using the DocBlocks, we can at least attempt to resolve the return types for functions and methods.

```php
/**
 * @return int|null
 */
public function aMethodReturningInt() { /* ... */ }
```

Implement a new method `getDocBlockReturnTypes()` which would return an array of `Type` objects. In this case, it would return something like a `[Types\Integer,Types\Null_]`

**Comment by Ocramius** [comment]
Handled in #104
