### ISSUE TITLE
ReflectionClass getMethods() and getProperties() do not filter

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#103]
http://php.net/manual/en/reflectionclass.getmethods.php
http://php.net/manual/en/reflectionclass.getproperties.php

The `getMethods()` and `getProperties()` both do not actually filter at all - they need to accept an integer parameter.

``` php
// Fetch all private methods
$classInfo->getMethods(ReflectionMethod::IS_PRIVATE);
```

**Comment by Ocramius** [comment]
Handled in #275
