### ISSUE TITLE
Make `CompileNodeToValue` semi-`@psalm-immutable`?

### ISSUE THREAD

**Issue by Ocramius** [Roave/BetterReflection#1043]
While working on:

 * https://github.com/Roave/BackwardCompatibilityCheck/issues/400
 * https://github.com/Roave/BackwardCompatibilityCheck/pull/476

I discovered that `CompileNodeToValue` internally uses `realpath()` and `dirname()` to chop off parts of file names.

This is problematic for any kind of processing where the `LocatedSource` does not have a file path, such as in serialized `LocatedSource` trees, where the filesystem is no longer accessible.

In addition to that, `realpath()` and `dirname()` do cause runtime stat calls to be avoided.

We should most likely adapt `CompileNodeToValue` to operate without attempting to access the filesystem (on its own) while evaluating constant expressions: `@psalm-immutable` is not achievable due to the large traversing of other reflection symbols, but we should get to a `@psalm-external-mutation-free` or similar scenario.

**Comment by theofidry** [comment]
>In addition to that, realpath() and dirname() do cause runtime stat calls to be avoided.

At least realpath could be replaced by (Symfony, previously webmozart) `Path::normalize()`

**Comment by Ocramius** [comment]
Would certainly copy over the code than introduce a dependency there 😬
