### ISSUE TITLE
Not all public properties in Adapter namespace work correctly

### ISSUE THREAD

**Issue by ondrejmirtes** [Roave/BetterReflection#1120]
There's currently an `unset` + `__get` hack for `ReflectionClass::$name`: https://github.com/Roave/BetterReflection/blob/c834c79e3c116346c830f4921a7aaafe2e35ea58/src/Reflection/Adapter/ReflectionClass.php#L38 + https://github.com/Roave/BetterReflection/blob/c834c79e3c116346c830f4921a7aaafe2e35ea58/src/Reflection/Adapter/ReflectionClass.php#L46-L53

We need to do a similar hack for other public properties. There's about 12 of them judging from https://github.com/JetBrains/phpstorm-stubs/tree/master/Reflection.

Otherwise we can get errors like `Error: Typed property ReflectionParameter::$name must not be accessed before initialization`.

Originally reported: https://github.com/phpstan/phpstan/issues/7428

**Comment by Ocramius** [comment]
Urgh, public properties @_@
