### ISSUE TITLE
ReflectionMethod Adapter: Calling setAccessible() shouldn't be needed for non-public methods as of PHP 8.1

### ISSUE THREAD

**Issue by ondrejmirtes** [Roave/BetterReflection#1121]
https://www.php.net/manual/en/reflectionmethod.setaccessible.php

> Note: As of PHP 8.1.0, calling this method has no effect; all methods are invokable by default. 

But the adapter here still requires it before calling `invoke()`: https://github.com/Roave/BetterReflection/blob/c834c79e3c116346c830f4921a7aaafe2e35ea58/src/Reflection/Adapter/ReflectionMethod.php#L238-L240

The options IMHO are:

1) Remove the `isAccessible()` check and be done with it.
2) Require it only when running on PHP 8 but not on PHP 8.1+.
3) Remove the `isAccessible()` check and set PHP 8.1 as a new minimum version.

Originally reported: https://github.com/phpstan/phpstan/issues/7429

**Comment by Ocramius** [comment]
We can just drop the check IMO.
