### ISSUE TITLE
`test` is not covered by static analysis

### ISSUE THREAD

**Issue by Ocramius** [Roave/BetterReflection#1122]
Discussed with @ondrejmirtes - `test/` is not covered by static analysis :scream: 

We should have both PHPStan and Psalm cover that ASAP, even if it means expanding the baseline by a lot.

**Comment by ondrejmirtes** [comment]
This definitely implies installing PHPUnit plugins for Psalm/PHPStan so that the code is correctly understood.

**Comment by kukulich** [comment]
PHPStan on `test/unit`
```
[ERROR] Found 839 errors
```

It looks I have something to do... 😃

**Comment by Ocramius** [comment]
@kukulich if you do want to work on it, please do first send an independent patch with just baseline additions, and then we do fix-ups afterwards

**Comment by kukulich** [comment]
Ok but it's a "small" task too :)

```
 [WARNING] Baseline generated with 782 errors.
Some errors could not be put into baseline. Re-run PHPStan and fix them.
```

**Comment by Ocramius** [comment]
> Some errors could not be put into baseline. Re-run PHPStan and fix them.

This has caused me some trouble on a closed source project today too: we either need to fix these, or do the baseline approach just with psalm 🤔

**Comment by kukulich** [comment]
It looks we cannot test unit tests with Psalm now:

```
Uncaught UnexpectedValueException: Intersection types not yet supported in P:\Git\better-reflection\vendor\vimeo\psalm\src\Psalm\Internal\PhpVisitor\Reflector\FunctionLikeNodeScanner.php:824
```

**Comment by Ocramius** [comment]
Owww, chaos

**Comment by kukulich** [comment]
With a little help of rubber duck @ondrejmirtes I now have "only" 57 errors to fix (and 748 in baseline) 😃

**Comment by kukulich** [comment]
@Ocramius Should we test fixtures or not?

**Comment by Ocramius** [comment]
I think not: they include purposely weird/wonky code, so they can't be put under static analysis.
