### ISSUE TITLE
`PhpInternalSourceLocator` and `EvaledCodeSourceLocator` can only stub classes

### ISSUE THREAD

**Issue by Ocramius** [Roave/BetterReflection#119]
As it stands, `PhpInternalSourceLocator` and `EvaledCodeSourceLocator` can only stub classes.

This is a limitation as per zendframework/zend-code#7

To fix it (for now), a simple solution is to apply a transformation to the output of `zendframework/zend-code`, but it is not sufficiently solid/stable.

**Comment by asgrim** [comment]
Handled in #120
