### ISSUE TITLE
Deprecate converting initializer expressions to runtime values?

### ISSUE THREAD

**Issue by ondrejmirtes** [Roave/BetterReflection#1222]
All the places where CompileNodeToValue is used are problematic because this feature has a possibility of involving runtime concepts into static reflection.

Initializers expressions (like property or parameter default values) can contain things that need to involve autoloading when converting to runtime values.

While `Foo::SOME_CONST` can be resolved statically because the `Foo` class can be statically reflected via BetterReflection and the `SOME_CONST` can have a scalar value, it's not possible to statically reflect expressions that resolve to objects, like `new` (supported since PHP 8.1 https://wiki.php.net/rfc/new_in_initializers) and `FooEnum::SOME_CASE` where it references an enum case. Creating a runtime object would inevitably lead to autoloading which might not be configured at all when running BetterReflection.

So code that uses CompileNodeToValue can sometimes work but not always. It's up to you to decide if it's worthy to have it if it's dangerous to be used because it cannot always work.

Personally I'd limit its usage only to the Adapter layer and nowhere else. Methods that use CompileNodeToValue in non-Adapter Reflection* classes should be deprecated/removed and the Adapter layer should use CompileNodeToValue with the AST expression from methods like `getValueExpr()`.

**Comment by Ocramius** [comment]
@ondrejmirtes how are we going to `CompileNodeToValue` if we didn't keep the AST in memory (precisely to prevent memleaks)?

**Comment by ondrejmirtes** [comment]
We're still keeping the related initializer AST expressions in memory. For example https://github.com/Roave/BetterReflection/blob/7bc326b042fe8840420f3c20554d8758a44b6dcf/src/Reflection/ReflectionParameter.php#L38

**Comment by Ocramius** [comment]
Ok, so we won't GC in those cases then :+1:

**Comment by Ocramius** [comment]
@ondrejmirtes see https://github.com/Roave/BetterReflection/pull/1223

**Comment by Ocramius** [comment]
Handled in #1223
