### ISSUE TITLE
`Roave\BetterReflection\Reflection\ReflectionFunctionAbstract#getStartColumn()` throws `RuntimeException` instead of `Roave\BetterReflection\Util\Exception\NoNodePosition`

### ISSUE THREAD

**Issue by Ocramius** [Roave/BetterReflection#1276]
https://github.com/Roave/BetterReflection/blob/55b947fe0b929ec6ec4d40d6b4a37b7e6bf2496b/src/Reflection/ReflectionFunctionAbstract.php#L349-L407

This API should probably throw `NoNodePosition`, to be more specific?

Would be a minor BC break, since `NoNodePosition extends InvalidArgumentException`

**Comment by Ocramius** [comment]
`NoNodePosition` may be wrong here: a more specific exception type would suffice, though. 

By extending `RuntimeException`, we would also prevent a BC break.

**Comment by kukulich** [comment]
Naming is hard... Do you have an idea how to name the exception?

**Comment by Ocramius** [comment]
Maybe `CodeLocationMissing` or such?
