### ISSUE TITLE
Reflection Adapter vs. non-empty-string

### ISSUE THREAD

**Issue by ondrejmirtes** [Roave/BetterReflection#1278]
This PR https://github.com/Roave/BetterReflection/pull/1234 made Adapter reflection incompatible with the native PHP reflection. The native reflection returns `false` in `has*` methods if it's asked about nonexistent elements, and throws ReflectionException in `get*` methods: https://3v4l.org/YebV9

But the `assert($name !== '');` calls are unforgiving even for `has*` methods. The current situation isn't great, because these methods have `string` in parameter types but reject `''` at runtime. So currently these problems cannot be detected and avoided with static analysis.

I'd prefer if the Adapter namespace matched the behaviour of native reflection:

For `has*` methods, instead of the assert, do this:

```php
if ($s === '') {
    return false;
}
```

For `get*` methods, throw ReflectionException for empty strings.

Thank you.

**Comment by Ocramius** [comment]
Doing this in the adapters sounds good 👍
