### ISSUE TITLE
Inconsistent capitalisation of method names in getDocBlock*

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#132]
https://github.com/Roave/BetterReflection/blob/master/src/Reflection/ReflectionFunctionAbstract.php#L397

```php
public function getDocblockReturnTypes()
```
(note lowercase B in `Docblock`)

whereas:

https://github.com/Roave/BetterReflection/blob/master/src/Reflection/ReflectionProperty.php#L181
```php
public function getDocBlockTypeStrings()
public function getDocBlockTypes()
```

and

https://github.com/Roave/BetterReflection/blob/master/src/Reflection/ReflectionParameter.php#L259
```php
public function getDocBlockTypeStrings()
public function getDocBlockTypes()
```

**Comment by asgrim** [comment]
http://www.phpdoc.org/docs/latest/guides/docblocks.html `DocBlock` is correct, will go with this

**Comment by Ocramius** [comment]
Handled in #137
