### ISSUE TITLE
Add methods to modify reflections

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#134]
It would be pretty cool to be able to modify a reflection, for example:

```php
$newProperty = ReflectionProperty::create('bar', \ReflectionProperty::IS_PRIVATE | \ReflectionProperty::IS_STATIC);
$reflectionClass->addProperty($newProperty);
```

This is a powerful feature when combined with the ability to export a reflection to PHP code (see #133).

**Comment by asgrim** [comment]
*Note: this sort of modification would modify the attached AST*

Possible ideas for modifications:

* Class::add/removeProperty
* FunctionAbstract::add/removeParameter
* Property::setVisibility
* (add more ideas here later)

**Comment by olimorris** [comment]
The `addMethod` idea would be very special. Unless you install runkit on your server, there's no neat way of actually monkey patching a method at runtime in PHP.

In terms of use cases, I'm using a third party package and need to add some specific functionality to the core of the package (namely two methods). A pull request would be too opinionated and a general fork would take me out of sync from the rest of the package.

**Comment by olimorris** [comment]
@asgrim this is brilliant. Great job.
