### ISSUE TITLE
no longer installs with Symfony

### ISSUE THREAD

**Issue by tacman** [Roave/BetterReflection#1403]
```bash
symfony new bug --webapp && cd bug && composer require roave/better-reflection
```

* Creating a new Symfony project with Composer
  (running /usr/local/bin/composer create-project symfony/skeleton /home/tac/trash/bug  --no-interaction)

* Setting up the project under Git version control
  (running git init /home/tac/trash/bug)

  (running /usr/local/bin/composer require webapp --no-interaction)

                                                                                                                        
 [OK] Your project is now ready in /home/tac/trash/bug                                                                  
                                                                                                                        

./composer.json has been updated
Running composer update roave/better-reflection
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - roave/better-reflection 0.1.0 requires nikic/php-parser dev-master -> found nikic/php-parser[dev-master, 5.0.x-dev (alias of dev-master)] but it does not match your minimum-stability.
    - roave/better-reflection[1.0.0, ..., 1.2.0] require php ^5.6|^7.0 -> your php version (8.3.2) does not satisfy that requirement.
    - roave/better-reflection 2.0.0 requires php >7.1.0,<7.3.0 -> your php version (8.3.2) does not satisfy that requirement.
    - roave/better-reflection[2.0.1, ..., 2.0.2, 3.0.0, ..., 3.1.1] require php >=7.1.0,<7.3.0 -> your php version (8.3.2) does not satisfy that requirement.
    - roave/better-reflection[3.2.0, ..., 3.3.0] require php >=7.1.0,<7.4.0 -> your php version (8.3.2) does not satisfy that requirement.
    - roave/better-reflection 3.4.0 requires php >=7.2.0,<7.4.0 -> your php version (8.3.2) does not satisfy that requirement.
    - roave/better-reflection[3.5.0, 4.0.0, ..., 4.3.0] require php >=7.2.0,<7.5.0 -> your php version (8.3.2) does not satisfy that requirement.
    - roave/better-reflection[4.4.0, ..., 4.12.2] require php >=7.4.1,<7.5.0 -> your php version (8.3.2) does not satisfy that requirement.
    - roave/better-reflection[5.0.0, ..., 5.10.0] require php ~8.0.12 || ~8.1.0 -> your php version (8.3.2) does not satisfy that requirement.
    - roave/better-reflection[5.11.0, ..., 5.11.1, 6.0.0, ..., 6.4.1] require php ~8.0.12 || ~8.1.0 || ~8.2.0 -> your php version (8.3.2) does not satisfy that requirement.
    - roave/better-reflection[6.5.0, ..., 6.17.0] require php ~8.1.0 || ~8.2.0 -> your php version (8.3.2) does not satisfy that requirement.
    - roave/better-reflection[6.18.0, ..., 6.19.0] require nikic/php-parser ^4.17.1 -> found nikic/php-parser[v4.17.1, v4.18.0] but the package is fixed to v5.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - roave/better-reflection[6.20.0, ..., 6.26.0] require nikic/php-parser ^4.18.0 -> found nikic/php-parser[v4.18.0] but the package is fixed to v5.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires roave/better-reflection * -> satisfiable by roave/better-reflection[0.1.0, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 2.0.0, 2.0.1, 2.0.2, 3.0.0, ..., 3.5.0, 4.0.0, ..., 4.12.2, 5.0.0, ..., 5.11.1, 6.0.0, ..., 6.26.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require roave/better-reflection:*" to figure out if any version is installable, or "composer require roave/better-reflection:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by asgrim** [comment]
PHP Parser v5 support is still being worked on: https://github.com/Roave/BetterReflection/pull/1387

**Comment by Ocramius** [comment]
Instead of `composer require roave/better-reflection`, pick an older release :)
