### ISSUE TITLE
`PhpStormStubsSourceStubber` calls into application autoloader

### ISSUE THREAD

**Issue by staabm** [Roave/BetterReflection#1415]
while debugging today, I realized that when BetterReflection is building up its reflection knowledge based on phpstorm stubs, it is invoking application autoloaders.

I found stacktraces like

![grafik](https://github.com/Roave/BetterReflection/assets/120441/76a66529-c6e9-4631-b98f-7c6094630a99)

in which you can see the top-level frame `Rocket::autoload`. thats my application autoloader which is registered via phpstan bootstrap file.

my questions:
- should BetterReflection trigger autoloading while analyzing phpstorm stubs?
- if autoloading is really needed, should better reflection isolate the autoloading involved from side-effects like a application level autoloader?

I came to this question, because our application autoloading needs todo some gymnastics and it is invoked a lot for all kind of classes which `BetterReflection` is locating while parsing stub files.

looking deeper it might even be the case this only happens from within PHPStan.. not sure yet

**Comment by kukulich** [comment]
> should BetterReflection trigger autoloading while analyzing phpstorm stubs?
> if autoloading is really needed, should better reflection isolate the autoloading involved from side-effects like a application level autoloader?

The autoload is not intentional. It looks it's triggered by `defined`. 

We use `updateConstantValue` because values in stubs are not actual or are different on different PHP versions or operating systems.

**Comment by staabm** [comment]
> It looks it's triggered by `defined`.

I wasn't aware `defined` can trigger autoloading, but you are right:

https://3v4l.org/pMmLA

**Comment by kukulich** [comment]
We can probably use `get_defined_constants`: https://3v4l.org/r3O9o

**Comment by staabm** [comment]
@kukulich I found a way on how it could work, please have  a look: https://github.com/Roave/BetterReflection/pull/1416

**Comment by kukulich** [comment]
@staabm I think it's very nice solution 👍
