### ISSUE TITLE
Add `getStartLine` and `getEndLine` to `BetterReflection\Reflection\Adapter\ReflectionEnumUnitCase`

### ISSUE THREAD

**Issue by ruudk** [Roave/BetterReflection#1430]
👋 Hi all, thanks for creating this amazing library.

When reflecting an enum, for each case, I want to know where it's defined.

This is possible on `BetterReflection\Reflection\ReflectionEnumCase` but not on `BetterReflection\Reflection\Adapter\ReflectionEnumUnitCase`.

Before I create the PR to address this, I want to know if this was an oversight? Or done on purpose.

**Comment by Ocramius** [comment]
@ruudk the adapters only mirror the API of `ext-reflection`, so we don't add any more API to them than what is declared in upstream.
