### ISSUE TITLE
Ability to create non-class/function reflections by Name

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#145]
e.g.:

```php
<?php
class Foo {
  public function bar() {}
}

$property = \BetterReflection\Reflection\ReflectionMethod::createFromName('Foo', 'bar');
```

Applies to:

* `ReflectionMethod::createFromName($classNameOrInstance, $methodName)`
* `ReflectionParameter::createFromName($closureOrArray, $parameterName)`
* `ReflectionProperty::createFromName($classNameOrInstance, $propertyName)`

**Comment by Ocramius** [comment]
You are not really "creating" it, so IMO `::fromClassAndName` and `::fromCallable` could be better :-)

**Comment by asgrim** [comment]
just going with the existing convention of calling things `createFromName`...

**Comment by Ocramius** [comment]
Alright :)
