### ISSUE TITLE
var_dump'ing a reflection is extremely slow

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#146]
I've disabled many `.phpt` tests in #139 because they use `var_dump` to check tests. This won't unfortunately work, but I noticed that using `var_dump` on a Better Reflection is excessively slow. I think this is related to `SourceStubber` and it's deps on PhpParser.

**Comment by asgrim** [comment]
(also applies to `print_r` it seems)

**Comment by Ocramius** [comment]
Dumping any object with a cyclic dependency is a suicide. This works for small dumps, but causes massive issues otherwise: https://3v4l.org/kLIGY

**Comment by asgrim** [comment]
Yarp, whatever cyclic thing is going on should be eliminated IMO... but then the .phpt tests need rewriting to not use `var_dump` anyway imo :P

**Comment by Ocramius** [comment]
> whatever cyclic thing is going on should be eliminated IMO

Not needed, really.

It is so easy to build a cyclic dependency, and especially since better-reflection is lazy-loading reflection, it cannot really be avoided.

**Comment by Ocramius** [comment]
Note: send all the complainers to me, eventually :-P

**Comment by lisachenko** [comment]
Shhhh, `__debugInfo()` method

**Comment by Ocramius** [comment]
NOOOOOOOOOOOOOOOOOOO

The only method in PHP that was deliberately created to make things more complicated to understand :-P
