### ISSUE TITLE
Method/Function - find function calls

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#154]
Inspired by: https://twitter.com/Ocramius/status/682249467148529666

Given a method / function / closure, e.g.: 

``` php
function myThing()
{
    $i = foo();
    return $i->whatever();
}
```

With a Method/Function reflection on this, it would be neat to be able to analyse the body AST, like:

``` php
$functionInfo = ReflectionFunction::createFromName('myThing');
$functionInfo->containsFunctionCall('foo'); // returns true
$functionInfo->getFunctionCalls('foo'); // returns array of AST nodes, or maybe a new VO wrapping info
$functionInfo->containsMethodCall('i', 'whatever'); // true
$functionInfo->getMethodCalls('i', 'whatever'); // array of whatever
```

**Comment by Ocramius** [comment]
Discussed in detail in #626: this should not be part of this library unless we manage to have PHI translation of code, so that we can inspect code usages via static analysis.
