### ISSUE TITLE
Review & improve documentation

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#161]
https://github.com/Roave/BetterReflection/blob/master/docs/features.md especially needs updating and more info put in about additional features (at least the ones above core reflection).

**Comment by GeeH** [comment]
@asgrim I'm happy to take this, however, realistically I need to know exactly what you need covered, as I've fallen of the curve with regards to features lately.

**Comment by asgrim** [comment]
Therein lies the problem :) I'm not sure what is useful currently without reviewing what we have currently. I'll try and find some time to see what we've got and what we could do with, that would hopefully be a useful starting point.

**Comment by Ocramius** [comment]
Handled in #207
