### ISSUE TITLE
Investigate upgrading to phpdocumentor/reflection-docblock 3.1

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#169]
Currently we're pegged on 2.0, but 3.0 is now out.

There's some changes in 3.0 which seem to break unit tests (mostly seems to be `Error: Class 'phpDocumentor\Reflection\DocBlock\Context' not found`, it may've just been renamed, or maybe something fundamental has changed so that we'd need to refactor.

Additionally, phpunit/phpunit 5 requires phpspec/prophecy which requires 2.0, which conflicts, so we'd have to alias it (`3.0.0 as 2.0.0` or something silly), or get them to allow `^2.0|^3.0`.

**Comment by asgrim** [comment]
Looking into this now, as conflicts with  symfony/symfony ^3.1

**Comment by podorozhny** [comment]
Guys, any info about when this PR will be released?

**Comment by Ocramius** [comment]
@podorozhny see https://github.com/Roave/BetterReflection/milestone/5 if you want to help out
