### ISSUE TITLE
All BetterReflection reflection classes should implement \Reflector

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#17]
Currently they don't... so make it so.

* [x] ReflectionClass
* [x] ReflectionFunction
* [x] ReflectionMethod
* [x] ReflectionParameter
* [x] ReflectionProperty

**Comment by asgrim** [comment]
I've started implementing this, but have discovered we *really* need to do #7 first otherwise this will be a mess

**Comment by Ocramius** [comment]
Is this supposed to be closed?

**Comment by asgrim** [comment]
Yes, was closed in pr #91 that YOU merged ;)
