### ISSUE TITLE
Use expectException instead of setExpectedException in tests

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#170]
see: https://thephp.cc/news/2016/02/questioning-phpunit-best-practices

For forwards compatibility, we need to modify calls to `setExpectedException` to use `expectException` and `expectExceptionMessage` instead. 

i.e.

instead of 
```php
$this->setExpectedException(
    InvalidArgumentException::class,
    'foo is not a valid identifier type'
);
```

we need to:

```php
$this->expectException(InvalidArgumentException::class);
$this->expectExceptionMessage('foo is not a valid identifier type');
```

**Comment by Ocramius** [comment]
I don't really understand the need for `expectException` vs `setExpectedException`. While the semantics are different, both make perfect sense :-\

**Comment by asgrim** [comment]
Yeah I sent a tweet querying why setExpectedException needs to be deprecated :/ https://twitter.com/asgrim/status/696320062823755776
