### ISSUE TITLE
FindParameterDescription does not exist

### ISSUE THREAD

**Issue by AydinHassan** [Roave/BetterReflection#172]
`\BetterReflection\Reflection\ReflectionParameter::getDocBlockDescription`

`FindParameterDescription` does not seem to exist! I think this one got missed in the tests haha

**Comment by Ocramius** [comment]
@AydinHassan could you point at the faulty code as well?

**Comment by AydinHassan** [comment]
oh god I'm such an idiot. Please ignore.
