### ISSUE TITLE
Feature request: Doc Block return description

### ISSUE THREAD

**Issue by AydinHassan** [Roave/BetterReflection#173]
It would be nice to able to grab the return type description from `ReflectionMethod` for example `getDocBlockReturnDescription`. Currently I'm having to use `\phpDocumentor\Reflection\DocBlock` directly which seems a bit flaky :smile: 

Or is this out of scope?

**Comment by Ocramius** [comment]
@AydinHassan I'd say that `phpDocumentor\Reflection\DocBlock` is doing a great job at it (we used it in a few projects), and it already works with BetterReflection, as far as I can remember...

**Comment by AydinHassan** [comment]
@Ocramius I didn't mean the quality of it, I just mean that it's parsed twice due to BetterReflection using it also and now I have to explicitly require it and if BetterReflection upgrades to 3.0 (I think I noticed that), I will have to update also (not a massive issue)

**Comment by Ocramius** [comment]
@AydinHassan the problem that I see is that PSR-5 is still not a thing, so we'd start supporting one type of docblock annotation while ignoring all the other weird formats.

**Comment by AydinHassan** [comment]
@Ocramius makes sense although it sort of complements `ReflectionParameter::getDocBlockDescription`. Does that suffer the same issues in regards to PSR5?

**Comment by AydinHassan** [comment]
Again ignore. Sorry for wasting your time. Couple of days ago I was going to add these features now I forget what I did and see they don't exist and try to blame you :(

**Comment by AydinHassan** [comment]
I'm so embarrassed, I will go hide now

**Comment by Ocramius** [comment]
@AydinHassan no worries :D
