### ISSUE TITLE
Extend core \ReflectionClass etc.

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#18]
Adapter for core Reflection classes, e.g.

```php
<?php

namespace BetterReflection\CompatibleReflection;

use \ReflectionClass as CoreReflectionClass;
use BetterReflection\Reflection\ReflectionClass as BetterReflectionClass;

class ReflectionClass extends CoreReflectionClass
{
    /**
     * @var BetterReflectionClass
     */
    private $betterReflection;

    public function __construct()
    {
        throw new \Exception("Cannot instantiate like this...");
    }

    public static function createFromNode(
        ClassNode $node,
        NamespaceNode $namespace = null,
        $filename = null
    ) {
        $reflection = new self();
        $reflection->betterReflection = BetterReflectionClass::createFromNode($node, $namespace, $filename);
    }

    // Implement all the core methods
}
```

Alternatively, just make `\BetterReflection\Reflection\ReflectionClass` extend `\ReflectionClass` and ensure every method is implemented...

Why? So that something that is (incorrectly) type hinting for `\ReflectionClass` instead of `\Reflector` can use this library...

**Comment by asgrim** [comment]
Note - we should avoid that exception in `__construct` and avoid implementing `createFromNode` thing - see #36 in order to be able to achieve this particular part. This task is only to provide classes that extend the core APIs, to ensure type hinting can work for things that typehint specifically to `ReflectionClass` etc.

**Comment by lisachenko** [comment]
+1 for making classes compatible with internal reflection. I have an experience with `PHP-Token-Reflection` library and it has serious disadvantage: it can return several different types of reflection (internal one or a parsed instance). This requires no typehints on methods and checks `instanceof TokenReflection\ReflectionClass` which are ugly.

So, if you agree to change the API a little bit, we can use inheritance and method overloading to cover all major functionality of reflection with the help of `PHP-Parser` lib. 

As I know, @TomasVotruba also tried to implement a static reflection on top of `PHP-Parser` for ApiGen needs (https://github.com/ApiGen/ElementReflection). But this project requires a lot of external dependencies.

**Comment by TomasVotruba** [comment]
@lisachenko It also requires lot of work, not really tested on any project.

**Comment by asgrim** [comment]
https://twitter.com/Ocramius/status/623194782110756864

**Comment by asgrim** [comment]
Needs #17

**Comment by asgrim** [comment]
hmm - {{BR\ReflectionObject}} could be difficult, as it currently extends {{BR\ReflectionClass}} :/ not sure how to solve this one as no multiple inheritance.

**Comment by asgrim** [comment]
`BR\ReflectionObject` can just inherit `\ReflectionObject` since it is a decorator anyway.

However, `BR\ReflectionMethod` and `BR\ReflectionFunction` are problematic because they use logic from `BR\ReflectionFunctionAbstract` :'(

**Comment by Ocramius** [comment]
Can `BetterReflection\ReflectionFunctionAbstract` extend from `ReflectionFunctionAbstract`?

**Comment by asgrim** [comment]
Yes of course, but `BR\ReflectionMethod` still can't extend
`\ReflectionMethod` etc.

**Comment by Ocramius** [comment]
True. Guess I just had a brain fart.

I suppose most systems type-hint against `ReflectionMethod` and `ReflectionFunction`. Should be ok with just those (for now)

**Comment by asgrim** [comment]
Still can't do that, as BR internal functionality is mostly in
`BR\ReflectionFunctionAbstract` so they still need to use multiple
inheritance :/

**Comment by asgrim** [comment]
I think the only way to do this is unfortunately with the adapter approach - means a lot of boilerplate code, but without multiple inheritance in the language, we can't directly do this (for `ReflectionFunction`/`ReflectionMethod` at least, and I'd prefer to stay consistent in approach.

**Comment by donquixote** [comment]
What about a trait `\BR\ReflectionFunctionTrait` instead of `\BR\ReflectionFunctionAbstract`?

This said, I am annoyed that the native PHP reflection API does not provide interfaces :(
This way, a function parameter that allows both native and custom reflection objects as argument, can never be type-hinted with an interface.

And I don't know what kind of ballast one gets by extending a native reflection class.

(I was going to write something similar myself, and dealing with the same issue. And then found both BetterReflection and PHP-Token-Reflection)

**Comment by lisachenko** [comment]
@donquixote there is one more )) Under active development, but almost ready: https://github.com/goaop/parser-reflection

PS. Just to compete and make our software better!

**Comment by donquixote** [comment]
@lisachenko Interesting!
Follow-up discussion there.. https://github.com/goaop/parser-reflection/issues/1

**Comment by donquixote** [comment]
bugs.php.net [Request #71037 Interfaces for Reflection API](https://bugs.php.net/bug.php?id=71037)

**Comment by nikic** [comment]
So what's up with the idea of using traits to solve this?

**Comment by Ocramius** [comment]
How would that actually work?

**Comment by nikic** [comment]
@Ocramius Replace `\BR\ReflectionFunctionAbstract` with a trait, use it in `BR\ReflectionFunction` and `BR\ReflectionMethod` which now extend `ReflectionFunction` and `ReflectionMethod`. I know it's distasteful, but it seems "good enough".
