### ISSUE TITLE
Can't composer install

### ISSUE THREAD

**Issue by olimorris** [Roave/BetterReflection#186]
Trying `composer require roave/better-reflection` I get the following:

```
  Problem 1
    - Installation request for jeremeamia/superclosure == 2.1.0.0 -> satisfiable by jeremeamia/SuperClosure[2.1.0].
    - roave/better-reflection 1.0.0 requires jeremeamia/superclosure ^2.2 -> satisfiable by jeremeamia/SuperClosure[2.2.0].
    - roave/better-reflection 1.0.1 requires jeremeamia/superclosure ^2.2 -> satisfiable by jeremeamia/SuperClosure[2.2.0].
    - Conclusion: don't install jeremeamia/SuperClosure 2.2.0
    - Installation request for roave/better-reflection ^1.0 -> satisfiable by roave/better-reflection[1.0.0, 1.0.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by asgrim** [comment]
Better Reflection requires at least SuperClosure 2.2.0 due to a version conflict with Php-Parser that SuperClosure/Better Reflection use. 2.2.0 makes them compatible. It looks like you (or a package you're requiring) explicitly requires 2.1.0. Try using `^2.2` if you can?

**Comment by olimorris** [comment]
Just tried and got:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install roave/better-reflection 1.0.1
    - Conclusion: remove nikic/php-parser v1.4.1
    - Installation request for roave/better-reflection ^1.0 -> satisfiable by roave/better-reflection[1.0.0, 1.0.1].
    - Conclusion: don't install nikic/php-parser v1.4.1
    - roave/better-reflection 1.0.0 requires nikic/php-parser ^2.0 -> satisfiable by nikic/php-parser[v2.0.0, v2.0.1].
    - Can only install one of: nikic/php-parser[v2.0.0, v1.4.1].
    - Can only install one of: nikic/php-parser[v2.0.1, v1.4.1].
    - Installation request for nikic/php-parser == 1.4.1.0 -> satisfiable by nikic/php-parser[v1.4.1].
```

Believe this is conflicts with Laravel...

**Comment by asgrim** [comment]
Could you gist your composer.json please? I'll try this when I get to my computer and see if I can resolve this conflict :)

**Comment by olimorris** [comment]
Yes sure. https://gist.github.com/olimorris/7ba1965ee433cd1d2d3a

**Comment by asgrim** [comment]
Hmm, I had to modify your composer.json to remove `laravel/spark` which seems to be a private package. Once I did that, I was able to `composer install`, then I was able to `composer require roave/better-reflection` just fine (see https://gist.github.com/asgrim/329becf97ee2357956f0#file-output-txt)

My only suggestion is that you've got an out of date dependency that forces the earlier nikic/php-parser version (1.4.1), which may be resolved with a `composer update`...

**Comment by olimorris** [comment]
Apologies! Yep I could. I longer peep into the repo so suspect that was the issue. Can't wait to press on with this and hopefully see an `addMethod` feature soon
