### ISSUE TITLE
Any way to get fully qualified class names in AST

### ISSUE THREAD

**Issue by moufmouf** [Roave/BetterReflection#195]
Hi guys,

First of all, congratulations for the great package. I've started working with it today, and it's really a pleasure to use.

I'm having one quick question:

When I parse the AST (for instance using `$method->getBodyAst()`), the class names I get (from class `PhpParser\Node\Name`) are not fully qualified (they are not taking into account the `use` statements declared at the beginning of the file).

In nikic/PHPParser, there is a node traverser that can resolve the FQCN:
https://github.com/nikic/PHP-Parser/blob/master/doc/2_Usage_of_basic_components.markdown#the-nameresolver-node-visitor

I'm wondering if there is any chance I could use this node traverser within BetterReflection. Is this possible? Did I miss something?

(if you are wondering why, I'm working on a code analyzer that translates basic PHP code (a factory method) into an object representing container definition)

**Comment by asgrim** [comment]
@moufmouf yes, it may be possible to use `FindTypeFromAst` which takes into account the `use` statements etc. by providing the `LocatedSource`. I imagine it looking something like:

```
$ast = $method->getBodyAst();

// do whatever you're doing to find the `PhpParser\Node\Name` node

$finder = new \BetterReflection\TypesFinder\FindTypeFromAst();
$type = $finder($theNameNode, $method->getLocatedSource(), $method->inNamespace ? $method->getNamespaceName() : '');
```

(I haven't tested this code, it's just off my head)

**Comment by asgrim** [comment]
Alternatively, you can simply feed `[$ast]` into a node traverser to do the same :)

**Comment by moufmouf** [comment]
Hey James,

Thanks a lot for the input. Using the `FindTypeByAst` class, I was able to solve my issue in a breaze.

The code I used:

```php
$finder = new FindTypeFromAst();
$type = $finder($className, $method->getLocatedSource(), $method->getDeclaringClass()->inNamespace() ? $method->getDeclaringClass()->getNamespaceName() : '');
```

Thanks a lot and congrats again for this great lib! Back to work now!

**Comment by asgrim** [comment]
You're welcome @moufmouf :)
