### ISSUE TITLE
Validate identifier name in Identifier value object

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#20]
Reported by @Ocramius in #3 ([here](https://github.com/Roave/BetterReflection/pull/3#discussion_r33802573))

> Consider validating `$name` against the regex `'/([a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]+)(\\\\[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]+)*/'`, as that's what a valid class name can refer to.
> 
> Only one segment for functions/methods.
> 
> See https://github.com/Ocramius/ProxyManager/blob/7badedb5f8afaaccd496a096daadb19d7bf2b374/tests/ProxyManagerTest/Inflector/ClassNameInflectorTest.php#L127

**Comment by Ocramius** [comment]
Handled in #341
