### ISSUE TITLE
Any reason for setting minimum PHP version to 5.6

### ISSUE THREAD

**Issue by aik099** [Roave/BetterReflection#201]
Any reason for setting minimum PHP version to 5.6 except that other are end of life?

Setting it to PHP 5.4 would be better.

**Comment by asgrim** [comment]
Yes, we use some 5.6 features such as variadics, argument unpacking, and also 5.4 is well out of support boundaries, and 5.5 is dropping security support very soon. You can try running it on older versions of PHP, but I'm afraid we won't be supporting earlier versions.

**Comment by Ocramius** [comment]
As a side-note: when are we dropping 5.x?

**Comment by GeeH** [comment]
Today.

**Comment by lisachenko** [comment]
@Ocramius @GeeH Why do you want to drop 5.x? Don't you forget that 5.6 is LTS and will be supported until 31 Dec 2016? Actually, it would be nice to fork master as 1.x and make it ~5.6|~7.0 and make master branch for ~7.0.

**Comment by asgrim** [comment]
@lisachenko yep, we'll drop 5.6 eventually anyway, not just yet though :)

**Comment by Ocramius** [comment]
@lisachenko libraries built for fun are a thing, libraries built for profit are a different matter. Reducing the surface of impact, especially for a library like this one (which highly depends on AST changes) simplifies things by a lot.

LTS means nothing in the context of free time (for me) anymore, from what I learned over the years. I know it sounds selfish.

Anyway, @asgrim's got control over that :-)

**Comment by lisachenko** [comment]
@Ocramius ok, your position is clear and perfectly valid )

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. ...

As an OS-developers we can publish our products for anyone, but we can get more respect from our community by keeping support for existing versions of libraries )

**Comment by Ocramius** [comment]
Yeah, I agree with that, I just don't eat nor buy clothes with respect  ;-)

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/
