### ISSUE TITLE
Autoload interruption for dynamic monkey patching

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#205]
A suggestion I had at DPC was to use a similar stream overriding technique to perform monkey-patched reflection loading. Investigate and see if this is possible!

/cc @Ocramius

**Comment by asgrim** [comment]
Test comment

**Comment by lisachenko** [comment]
I can confirm, that it's doable )

**Comment by asgrim** [comment]
Thanks :)

**Comment by Ocramius** [comment]
🚢
