### ISSUE TITLE
Support for PHP 5.5?

### ISSUE THREAD

**Issue by dantleech** [Roave/BetterReflection#211]
I realise that @Ocramius will probably be against this in principle, but, is there any reason not to support 5.5?

Currently this is the only thing preventing me from using [BR in PHPBench](https://github.com/phpbench/phpbench/pull/429).

The issue is that it is used in CI (for example the Zend libraries) which still support 5.5.

If this is not possible, then its no big deal. I will just wait for a year or so before merging the above PR as it is awesome but non-critical.

**Comment by asgrim** [comment]
PHP 5.5 isn't supported by PHP, so it wouldn't make sense to support an older version really :/ sorry.

In theory it might work on PHP 5.5 (maybe some language features need tweaking), and you're welcome to try it out, but I'm afraid we won't provide "official" support there.
