### ISSUE TITLE
Detect dead/unreachable AST nodes

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#215]
BR has the potential to detect dead code by reading the AST. Would this be useful?

**Comment by Ocramius** [comment]
@asgrim can be done, but doesn't sound simple. Things like `goto` have to be taken in consideration, for example.

**Comment by asgrim** [comment]
Yes, I never said it was simple; it may also not be useful as VLD already supports this (using opcodes, rather than AST). It was just theoretical and an idea from Derick's talk I just saw.

**Comment by Ocramius** [comment]
Another issue with this is that it's not reflection anymore, but just AST
traversal/optimization. Can possibly be done with a separate tool.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by Ocramius** [comment]
Closing here: I think this is up for static analysis tools, and not to BetterReflection itself.
