### ISSUE TITLE
Check compatibility with PHP 7.2

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#219]
Currently `.travis.yml` doesn't check PHP `nightly` (or even `7.1` for that matter) so we should add that in.

Related, and may be of relevance to this: https://twitter.com/WyriHaximus/status/796016769525809152

Thanks for hat tip to @WyriHaximus

**Comment by WyriHaximus** [comment]
No problem @asgrim, I'll try to uncover more details and keep you posted. Also you might want to put `nightly` on allowed to fail for now as it's codebase is volatile.

**Comment by Ocramius** [comment]
Note: 7.2 cannot really be tested in depth without Zend\Code supporting it (yet)

**Comment by WyriHaximus** [comment]
Think I just ruled out an issue with `ReflectionClass::getDocComment`, will continue digging to see why the code behaves in unexpected ways: https://twitter.com/WyriHaximus/status/796094099858321409

**Comment by WyriHaximus** [comment]
The issue has been uncovered, calling `get_class` with null as argument is deprecated in 7.2, [https://twitter.com/kelunik/status/796098864419835904](https://twitter.com/kelunik/status/796098864419835904), and thus raises an error. As demonstrated at https://travis-ci.org/WyriHaximus/php-7.2-tests/jobs/174334333#L177 with [https://github.com/WyriHaximus/php-7.2-tests/blob/master/test.php](https://github.com/WyriHaximus/php-7.2-tests/blob/master/test.php) Origin RFC: https://wiki.php.net/rfc/get_class_disallow_null_parameter

Sorry for jumping the gun a wee bit :blush:

**Comment by asgrim** [comment]
Ah yes, that makes sense. Thanks for reporting back @WyriHaximus :)

**Comment by WyriHaximus** [comment]
No problem @asgrim, it is the least I can do :)

**Comment by kukulich** [comment]
This could be closed probably.

**Comment by Ocramius** [comment]
Can indeed be closed: handled in https://github.com/Roave/BetterReflection/pull/316
