### ISSUE TITLE
isOptional determination is a mess

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#22]
It _does_ work but there is a mess of code in [ReflectionFunctionAbstract::setNodeOptionalFlag](https://github.com/Roave/BetterReflection/blob/11800e85f8c37c537e514f06cb929e49202d397c/src/Reflection/ReflectionFunctionAbstract.php#L67)

``` php
/**
 * We must determine if params are optional or not ahead of time, but we
 * must do it in reverse...
 */
private function setNodeOptionalFlag()
{
    $overallOptionalFlag = true;
    $lastParamIndex = (count($this->node->params) - 1);
    for ($i = $lastParamIndex; $i >= 0; $i--) {
        $hasDefault = ($this->node->params[$i]->default !== null);
        // When we find the first parameter that does not have a default,
        // flip the flag as all params for this are no longer optional
        // EVEN if they have a default value
        if (!$hasDefault) {
            $overallOptionalFlag = false;
        }
        $this->node->params[$i]->isOptional = $overallOptionalFlag;
    }
}
```

A simple solution would be to say something like (pseudo code) `if parameterindex > numrequiredparams, this param is optional` - however, on checking `getNumberOfRequiredParameters()` this has a cyclic dependency on `isOptional()` calls... which means they wouldn't be resolved at creation-time. Solve this somehow.

**Comment by asgrim** [comment]
Incidentally, I think #34 may provide some kind of a workaround for this?

**Comment by Ocramius** [comment]
This does not need fixing for now: closing as `wontfix`
