### ISSUE TITLE
Implement internal parsing of closures

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#228]
At the moment we rely on a tiny piece of SuperClosure library to reflect on closures. However, it wouldn't be too difficult to bring that in house. Reason being, we're at the mercy of SuperClosure to update dependency on PhpParaer all the time. It's happened twice now and blocked us, and for no good reason.

**Comment by jeremeamia** [comment]
I would actually _encourage_ you to decouple from SuperClosure. It's not something I'm going to put much effort into going forward. It almost seems like BetterReflection would be a logically better home for the part of SuperClosure you are using anyway.

**Comment by asgrim** [comment]
Thanks for feedback @jeremeamia! I mostly used it because "well, it does what we want, and I'm lazy" reasons, but I agree; coupling to a library for just that small feature was a mistake ;) thanks!

**Comment by asgrim** [comment]
Fixed in #321
