### ISSUE TITLE
Inherited properties not returned by getProperties

### ISSUE THREAD

**Issue by dantleech** [Roave/BetterReflection#231]
Currently only properties from the "top" class are returned by `ReflectionClass#getProperties`, in contrast with `getMethods` which returns inherited methods.

**Comment by asgrim** [comment]
Note: when fixing this, we need to exclude `private` properties in parent classes to replicate PHP behaviour:

```php
class Foo
{
  private $a;
}

class Bar extends Foo
{
  public $b;
}

$r = new \ReflectionClass(Bar::class);
var_dump($r->getProperties());
```

In this example, `$a` is not output, but if it's changed to `protected` or `public`, it is visible (as one would expect by the inheritance rules)

**Comment by asgrim** [comment]
Handled in #271
