### ISSUE TITLE
Reflection breaks when using JsonSerializable

### ISSUE THREAD

**Issue by kdambekalns** [Roave/BetterReflection#233]
When reflecting a class that implements `JsonSerializable` I get back an `IdentifierNotFound` exception:

`BetterReflection\Reflection\ReflectionClass "JsonSerializable" could not be found in the located source`

Any hints?

**Comment by asgrim** [comment]
This works using the default reflector:

```php
<?php
require_once 'vendor/autoload.php';

$ref = BetterReflection\Reflection\ReflectionClass::createFromName('JsonSerializable');
echo $ref->getName() . "\n";
```

so I'm assuming you're using a custom set of source locators. If that's the case, you'll also need to include `\BetterReflection\SourceLocator\Type\PhpInternalSourceLocator` in your aggregate source locator so BR can "find" internal classes too.

**Comment by kdambekalns** [comment]
Awesome, thanks for the ⚡️-fast response. Indeed that works. Admittedly I suspected internal classes to "always be there", but that's just me. Thanks again!
