### ISSUE TITLE
Improve the unit test suite further

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#24]
* Improve what tests are running
* Improve coverage by writing more tests
* Use `@covers` annotations to limit cover leakage

# Acceptable coverage in:
* [x] Identifier (see #32) - 94%
* [x] NodeCompiler (see #32) - 82%
* [x] Reflection (see #65 and 59)
* [x] Reflector (see #65)
* [x] SourceLocator (see #32) - 97%
* [x] TypesFinder (see #28) - 100%

**Comment by asgrim** [comment]
As of today: 
![coverage](https://cloud.githubusercontent.com/assets/496145/8499571/48c21c9e-218c-11e5-945a-5e4da60a5fcb.png)

**Comment by asgrim** [comment]
![co](https://cloud.githubusercontent.com/assets/496145/8696473/7ce5c35c-2ae4-11e5-93e4-8889e38f909a.png)

and now

**Comment by Ocramius** [comment]
@asgrim is the node compiler incorrectly covered?

**Comment by asgrim** [comment]
@Ocramius no, it is the `@todo` and issue #19 (see PR #65)
