### ISSUE TITLE
Requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by denmasyarikin** [Roave/BetterReflection#249]
I try to install in Laravel 5.4.11, but error has occoured : 

Problem 1
    - Installation request for roave/better-reflection ^1.2 -> satisfiable by roave/better-reflection[1.2.0].
    - Conclusion: remove nikic/php-parser v3.0.4
    - Conclusion: don't install nikic/php-parser v3.0.4
    - roave/better-reflection 1.2.0 requires nikic/php-parser ^2.0 -> satisfiable by nikic/php-parser[v2.0.0, v2.0.1, v2.1.0, v2.1.1].
    - Can only install one of: nikic/php-parser[v2.0.0, v3.0.4].
    - Can only install one of: nikic/php-parser[v2.0.1, v3.0.4].
    - Can only install one of: nikic/php-parser[v2.1.0, v3.0.4].
    - Can only install one of: nikic/php-parser[v2.1.1, v3.0.4].
    - Installation request for nikic/php-parser (locked at v3.0.4) -> satisfiable by nikic/php-parser[v3.0.4].

I don't know who has used nikic/php-parser in laravel dependencies.... how i fix this?

**Comment by asgrim** [comment]
Could you post your `composer.json` requirements please?

**Comment by denmasyarikin** [comment]
here.., it's just my dummy project

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "doctrine/dbal": "^2.5",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "Flipbox\\OrmManager\\": "/Users/dedenmaulana/Documents/Projects/Flipbox/flipboxstudio/orm-manager/src/Flipbox/OrmManager/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    }
}

**Comment by Ocramius** [comment]
Probably due to an old superclosure version.

Anyway, don't use just `>=` for dependencies (your PHP version dependency), as that's unsafe.

This is only fixable by upgrading superclosure to use PHP-Parser v3.

You can further explore the conflict with `composer why-not <package-name>`.

Meanwhile, closing as `invalid`
