### ISSUE TITLE
Possible unused code path

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#257]
https://github.com/Roave/BetterReflection/blame/990c87957536bebe092af47fa7cf710759e3226d/src/SourceLocator/Type/PhpInternalSourceLocator.php#L32

```php
        if ($stub = $this->getStub($name)) {
            return [
                "<?php\n\n" . $stub,
            ];
        }
```

This code doesn't look used, and disagrees with the contract imposed by the abstract `createLocatedSource` (should return `?LocatedSource`). Investigate and remove if unused.

**Comment by Ocramius** [comment]
@asgrim I think that's only used when stubs are in place - currently, we're lacking a lot there...

**Comment by asgrim** [comment]
There's no test coverage that I found; tried sticking a breakpoint there during tests, didn't stop... maybe it was in the skipped tests though, I didn't look hard enough possibly.

**Comment by Ocramius** [comment]
Yeah, that's because the stubs PR got stuck :P

**Comment by Ocramius** [comment]
Handled in https://github.com/Roave/BetterReflection/pull/344
