### ISSUE TITLE
Use jetbrains/phpstorm-stubs?

### ISSUE THREAD

**Issue by dantleech** [Roave/BetterReflection#261]
Found out about this package: https://github.com/JetBrains/phpstorm-stubs, maybe useful here?

**Comment by TomasVotruba** [comment]
@dantleech How exactly? Could you elaborate?

**Comment by asgrim** [comment]
Great find @dantleech, that looks possible!

**Comment by Ocramius** [comment]
Only if the stubs are in sync though...

**Comment by TomasVotruba** [comment]
Could anyone tell what is that for? To test this tool on various use cases?

**Comment by asgrim** [comment]
For reflection of internal PHP classes and functions. We have a hybrid of some Zend\Code related stuff and stubs at the moment.

**Comment by TomasVotruba** [comment]
Thanks for reply.

I'm still not sure I understand. So phpstorm-stubs are useful for testing reflection of internal PHP classes and functions out?

**Comment by asgrim** [comment]
In theory it is used here: https://github.com/Roave/BetterReflection/blob/master/src/SourceLocator/Type/PhpInternalSourceLocator.php#L35

**Comment by asgrim** [comment]
Related: #257

**Comment by dantleech** [comment]
They are so you can reflect internal php classes and functions.

On 15 May 2017 12:19:41 BST, "Tomáš Votruba" <notifications@github.com> wrote:
>Thanks for reply.
>
>I'm still not sure I understand. So phpstorm-stubs are useful for
>testing reflection of internal PHP classes and functions out?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Roave/BetterReflection/issues/261#issuecomment-301446982

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by TomasVotruba** [comment]
Thank you both. Referencing code in application helped me to better understand it.

**Comment by theofidry** [comment]
Can be closed as of #373

**Comment by Ocramius** [comment]
Thanks @theofidry!
