### ISSUE TITLE
Support PHP4-style constructors?

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#263]
https://github.com/Roave/BetterReflection/pull/258#discussion_r109134282

> TBH, could be php4 ctor... unsure though...
> php4 ctors only work with non-namespaced code (hint)

**Comment by TomasVotruba** [comment]
Is this feature really needed in PHP 7.1 days?

**Comment by roukmoute** [comment]
Against because it's been now 8 years and 9 months ago that PHP 4 is at end of life.
If server is always in PHP 4, it is just... dangerous, it is urged to upgrade to a current version.

**Comment by Ocramius** [comment]
This has nothing to do with being against or for it: this is PHP behaviour
and the reflection API does allow introspecting it.

**Comment by TomasVotruba** [comment]
I understand technical reasons and nice to have. 
Is that a priority or is PHP 5 behavior support preffered?

**Comment by Ocramius** [comment]
This is PHP 7 behaviour too: https://3v4l.org/rgA0q

**Comment by TomasVotruba** [comment]
I mean what's the use case.

**Comment by Ocramius** [comment]
The use-case is reflecting existing code: it could be the worst code in the
world, but a constructor is a constructor, so it should be detected as
such. Being opinionated about skipping it introduces false reflection
behaviour, and therefore bugs.

This library could be used to analyse code like WordPress', fwiw: it is not
up to us to decide.

**Comment by TomasVotruba** [comment]
I see. I just ask, because I came over few bugs but didn't report them, because I though they are quite rare in practice and might rapidly slow down evolution of this package. That happens traditionally for many open-source packages I see.

I get feeling from this response, that everything is important here. Should I report every possible fail cases I came across then?

**Comment by Ocramius** [comment]
Yes please: if this library is not behaving like reflection, or at least
providing equivalent information, then that's a bug.

**Comment by TomasVotruba** [comment]
Thanks, will do so.

**Comment by Ocramius** [comment]
Handled in #320
