### ISSUE TITLE
ReflectionMethod::isDestructor is case insensitive

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#264]
https://github.com/Roave/BetterReflection/pull/258#discussion_r109134941

```php
<?php

class Foo
{
    public function __dEsTrUcT() { var_dump(__METHOD__); }
}

new Foo;
```

**Comment by Ocramius** [comment]
This applies also to `isConstructor()` and eventually other magic methods

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/
