### ISSUE TITLE
Should `setStaticPropertyValue` trigger autoloading?

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#265]
> https://github.com/Roave/BetterReflection/pull/258#discussion_r109134565

Currently, we throw a `ClassDoesNotExist` exception if the class has not yet been loaded yet. Discuss whether we should just trigger autoloading, and also how the hijacked autoloader might work with that.

**Comment by Ocramius** [comment]
As of https://github.com/Roave/BetterReflection/blob/4be7704b058915d3b3f681560d8bdc76d7b1e252/src/Reflection/ReflectionProperty.php#L397 ( https://github.com/Roave/BetterReflection/pull/343 ) it does

**Comment by kukulich** [comment]
No, the check is still there: https://github.com/Roave/BetterReflection/blob/4be7704b058915d3b3f681560d8bdc76d7b1e252/src/Reflection/ReflectionProperty.php#L394

**Comment by Ocramius** [comment]
Gotcha, totally missed it @_@

**Comment by Ocramius** [comment]
Closing here: the question itself is answered
