### ISSUE TITLE
How to autoload parent class, that is not in the located source?

### ISSUE THREAD

**Issue by TomasVotruba** [Roave/BetterReflection#276]
#question

I'm not sure how to deal with this and I need help after couple hours of debugging.

I've prepared failing test, where you can read failing case: 

- https://github.com/ApiGen/ApiGen/blob/cea6ecd685d56660f3d97e301bf5f0f83c64c2d8/packages/Reflection/tests/Parser/ParseClassWithParentFromAnotherSourceTest.php#L22

- [Class in the `/Source` directory](https://github.com/ApiGen/ApiGen/blob/cea6ecd685d56660f3d97e301bf5f0f83c64c2d8/packages/Reflection/tests/Parser/Source/ClassWithParentFromAnotherSource.php)  
- [ParentClass in `/AnotherSource` directory](https://github.com/ApiGen/ApiGen/blob/cea6ecd685d56660f3d97e301bf5f0f83c64c2d8/packages/Reflection/tests/Parser/AnotherSource/ParentClassFromAnotherSource.php):

I load `ClassWithParentFromAnotherSource` class reflection from `/Source` directory - :heavy_check_mark: 

I want to get its parent class (`$reflectionClass->getParentClass()`), but it is not locaed in `/Source` :no_entry_sign: 

---

In real life, it's probably in the `/vendor`, like `MyController extends FrameworkBundle\Controller`. 

**How to get parent class without parsing whole `/vendor`?**

**Comment by asgrim** [comment]
Better Reflection cannot reflect on a class it does not know how to locate. You must either have it autoloadable (then the defaults should be fine), or if you're using a custom SourceLocator (or aggregate thereof) you need to include the other source.

**Comment by asgrim** [comment]
See: https://github.com/Roave/BetterReflection/blob/master/docs/usage.md#sourcelocators

**Comment by TomasVotruba** [comment]
> You must either have it autoloadable (then the defaults should be fine)

What does it exactly mean? I use composer and class is autoloadable.

> You need to include the other source.

That was my question, I don't want to add whole `/vendor` - or should I? How exactly would you doo that so it is automated?

**Comment by TomasVotruba** [comment]
Did you mean something [like this](https://github.com/Roave/BetterReflection/blob/master/docs/usage.md#using-the-composer-autoloader-directly)?

**Comment by asgrim** [comment]
It depends how you're doing the reflection of the class initially; the ClassReflector you're using must be able to locate the source. If you're using the default locators (e.g. if you used `ReflectionClass::createFromName($...)`) then it should be able to locate the file, as long as the class is located in a file on disk (that's usually the case).

You don't need to add the whole `/vendor` directory; as long as Composer has already been loaded, the `AutoloadSourceLocator` (which is in the default set of locators) will locate it fine.

If you're using a custom locator, you should add the autoload one too, e.g.:

```
$reflector = new ClassReflector(new SingleFileSourceLocator($filename));
$reflectionClass = $reflector->reflect(MyClass::class);
```

change it to something like:

```
$reflector = new ClassReflector(new AggregateSourceLocator([
    new SingleFileSourceLocator($filename),
    new AutoloadSourceLocator()
]));
$reflectionClass = $reflector->reflect(MyClass::class);
```

This way, the reflector will look in the specified file first, and then autoload it if it can't find it.

**Comment by TomasVotruba** [comment]
**Thanks a lot for before/after example!** It was easy to understand and set it up than.

https://github.com/ApiGen/ApiGen/pull/862/commits/dd6c05d734a3c6eef93ee5633a56d4a415d4acd7#diff-c6fd3b74b6d964000fb3420378fcced0L128

Works like a charm. Ever better :clap: 

If I understand that correctly, it will try to load class via `class_exists()`, right?

**Comment by TomasVotruba** [comment]
Btw, this looks like something very useful to know. I would say most of the code depends on something in `/vendor`, so this will came acrross any usage.

Could I added it to example (where I looked for this initially)?

**Comment by asgrim** [comment]
> If I understand that correctly, it will try to load class via class_exists(), right?

Yes, but it's not as straightforward as just that; we have to 1) prevent the autoloader from actually loading and 2) know which file the autoloader tried to load:

> this is a little hacky, but works on the assumption that when a registered autoloader identifies a file and attempts to open it, then that file will contain the class. Internally, it works by overriding the file:// protocol stream wrapper to grab the path of the file the autoloader is trying to locate. This source locator is used internally by the ReflectionClass::createFromName static constructor.

(see https://github.com/Roave/BetterReflection/blob/master/docs/usage.md#sourcelocators)

> Could I added it to example (where I looked for this initially)?

You're using a "sort of" an edge case; when you do `ReflectionClass::createFromName` it is using "sane defaults": https://github.com/Roave/BetterReflection/blob/master/docs/usage.md#basic-reflection :

> If this instantiation technique is not possible - for example, your autoloader does not load classes from file, then you must use SourceLocator creation.
> 
> Fun fact... using ReflectionClass::createFromName actually uses a SourceLocator under the hood - it uses the AutoloadSourceLocator.

I think it's definitely worth clarifying that if you want to do something "outside the box" then it's possible: the docs are there, just perhaps not worded best :)

**Comment by TomasVotruba** [comment]
> Yes, but it's not as straightforward as just that.

Thanks for explaining, I usually need to understand the gist 1 one line to be able to use it.

> I think it's definitely worth clarifying that if you want to do something "outside the box" then it's possible: the docs are there, just perhaps not worded best :)

Does that mean I can send PR? Docs is to detailed for this use case, I'd like to see it [in examples](https://github.com/Roave/BetterReflection/tree/master/demo/basic-reflection)

**Comment by asgrim** [comment]
Yes :) PRs always welcome!

**Comment by TomasVotruba** [comment]
Allright! :)
