### ISSUE TITLE
Reflect on instances of anonymous classes

### ISSUE THREAD

**Issue by marcosh** [Roave/BetterReflection#279]
At the moment it is not possible to reflect on instances of anonymous classes. In fact

```php
\Roave\BetterReflection\Reflection\ReflectionObject::createFromInstance(new class() {});
```

throws a `Roave\BetterReflection\Reflector\Exception\IdentifierNotFound` exception.

This actually works with standard reflection: [https://3v4l.org/aHbmW](https://3v4l.org/aHbmW)

From what I saw, it seems that the problem comes from the fact that `Roave\BetterReflection\SourceLocator\Ast\FindReflectionsInTree` does not inspect beyond the first level of the AST

**Comment by kukulich** [comment]
I hope it's resolved in https://github.com/Roave/BetterReflection/pull/300

**Comment by kukulich** [comment]
@Ocramius Could you please close this? :)

**Comment by Ocramius** [comment]
:+1:

**Comment by Ocramius** [comment]
Handled in #300
