### ISSUE TITLE
[PHP7.1] ::getReflectionConstant() and ::getReflectionConstants() support

### ISSUE THREAD

**Issue by POPSuL** [Roave/BetterReflection#281]
Now we have public/private/protected constants in classes, but we don't have opportunity for getting visibility level.

Related:
https://bugs.php.net/bug.php?id=74261
#204
https://github.com/ApiGen/ApiGen/issues/877

**Comment by asgrim** [comment]
Thanks for the report; good suggestion for compatibility

**Comment by POPSuL** [comment]
I will do pr to solve this issue within an hour

**Comment by Ocramius** [comment]
Handled in #282
