### ISSUE TITLE
ReflectionParameter::getDefaultValue() not parsing class constant

### ISSUE THREAD

**Issue by nikolaposa** [Roave/BetterReflection#283]
Particular case when this was failing was when integrating this pre-release version of my library depending on BetterReflection **1.2.0**: https://github.com/nikolaposa/cascader/tree/0.1.0. Exact part of code that was failing: https://github.com/nikolaposa/cascader/blob/0.1.0/src/Cascader.php#L87.

So what happened when I tried to integrate it in a dependent library: https://github.com/nikolaposa/monolog-factory was a call that evaluates to something like this:

```php
$object = (new Cascader())->create(\Monolog\Handler\NativeMailerHandler::class, [
    'to' => 'test@example.com',
    'subject' => 'Test',
    'from' => 'noreply@example.com',
]);
```

... which in the end resulted in `IdentifierNotFound` exception: `Class "Logger" could not be found in the located source`, when parsing `$level` argument of the `NativeMailerHandler` constructor: https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/NativeMailerHandler.php#L75

**Comment by asgrim** [comment]
@nikolaposa can you provide an isolated example, sorry :/ I'm wondering if you're using a custom `SourceLocator` or the defaults?

**Comment by nikolaposa** [comment]
Hi @asgrim,

Yeah, I know that this is not a helpful issue description at all, sorry for that. I was using default source locator, so without any sort of custom configuration.

I guess I should try to come up with some more concrete example.

**Comment by nikolaposa** [comment]
I think I'm gonna close this stale issue. I made I mistake by not opening it as soon as it happened, before I switched to alternative solution. Perhaps it had to do something with a setup I used in that particular situation when it happened (Windows + Vagrant). 

Anyway, if it ever happens again, I'll open a new issue with details how to reproduce it.
