### ISSUE TITLE
Release 2.0.0?

### ISSUE THREAD

**Issue by Ocramius** [Roave/BetterReflection#295]
We accumulated a few major improvements over the last months. @asgrim is anything worth holding off a release?

As far as I can see, we're pretty much on par with 7.2 once the current PRs are handled.

3.0.0 (or 2.1.0) could focus on performance, maybe.

**Comment by asgrim** [comment]
Yar, I think we're almost there too, we were mainly waiting for library updates (in phpdoc for example) which are done now, so shouldn't be a problem I think after #294 is merged at least.

**Comment by Ocramius** [comment]
@asgrim #294 is in :+1:

**Comment by jaapio** [comment]
you might want to update the phpdoc libs to there latest versions :-) for better php 7.2 support

**Comment by asgrim** [comment]
I think we can release `2.0.0` now...

**Comment by asgrim** [comment]
Note: phpdoc libs issue I made in #334, we can handle after `2.0.0` I reckon.

**Comment by Ocramius** [comment]
Delaying further, as I will work on BR today. Sorry 😥

**Comment by asgrim** [comment]
@Ocramius how are we looking now? :)

**Comment by kukulich** [comment]
I'm working on last PR for 2.0.0. It should be ready for review today.

**Comment by Ocramius** [comment]
@kukulich if that list complete now? If so, I can prepare a release tomorrow :+1:

**Comment by kukulich** [comment]
@Ocramius I found one bug a hour ago but PR should be prepared in a while :)

**Comment by kukulich** [comment]
Ok, I'm done :)

**Comment by Ocramius** [comment]
Had issues with train wifi the last few days, but managed to finally get it working: preparing release notes and release blogpost :+1:

**Comment by TomasVotruba** [comment]
Amazing work, thank you!

Can I help you with some simple post to spread the word?
Something in type and size of: https://www.tomasvotruba.cz/blog/2017/01/28/why-I-switched-scrutinizer-for-phpstan-and-you-should-too/

**Comment by Ocramius** [comment]
I still support scrutinizer-ci, so I really can't spread that 😅

**Comment by Ocramius** [comment]
Closing here meanwhile: this is done.

**Comment by asgrim** [comment]
I think @TomasVotruba meant to help by suggesting a new blog post (rather than that one, that was just an example?)

**Comment by Ocramius** [comment]
Ah, sorry, multitasking. Indeed, that post is ~8 months old ^_^

**Comment by TomasVotruba** [comment]
> I think @TomasVotruba meant to help by suggesting a new blog post (rather than that one, that was just an example?)
 :+1: 1  


Yep :+1:
