### ISSUE TITLE
Adapters API is not consistent with internal reflection

### ISSUE THREAD

**Issue by kukulich** [Roave/BetterReflection#304]
For example:

- `ReflectionClass::getParentClass()` - internal reflection returns `false` if class doesn't have parent, adapter returns `null`
- `ReflectionClass::getDocComment()` - internal reflection returns `false` if there is no doccoment, adapter returns `null`

See https://3v4l.org/iItg9

May I prepare pull request to fix it? Or it will not be merged because of BC break?

**Comment by Ocramius** [comment]
> May I prepare pull request to fix it?

Absolutely! Thanks if you do!

 > Or it will not be merged because of BC break?

The internal API adapters try to mimic the internal reflection API, so we honor that, regardless how broken it may be :-)

**Comment by kukulich** [comment]
Pull request: https://github.com/Roave/BetterReflection/pull/313

**Comment by Ocramius** [comment]
Handled in #313
