### ISSUE TITLE
Coding standard check

### ISSUE THREAD

**Issue by kukulich** [Roave/BetterReflection#326]
I would like to prepare coding standard check based on [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer).

1. Are you ok with the usage of PHP_CodeSniffer ? I know there was [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) already but PHP_CodeSniffer has much less dependencies.

2. Which codind standard should I use? PSR-2?

**Comment by Ocramius** [comment]
PSR-2 is sufficient for now: phpcs is the way to go indeed, plus we already
depend on it 👍

**Comment by kukulich** [comment]
Implemented in https://github.com/Roave/BetterReflection/pull/328
