### ISSUE TITLE
Property from Trait should have actual class as declaring class

### ISSUE THREAD

**Issue by kukulich** [Roave/BetterReflection#327]
See https://3v4l.org/sKOMg

Should I fix it only for adapter or should it be fixed in `BetterReflectionClass`?

I will have to add public method `BetterReflectionClass::getReflector()` for fix it only in adapter.

**Comment by Ocramius** [comment]
Not sure about this one, but I feel that the internal reflection API is kinda bad in this case. There should be separate endpoints to get the declaring class and the implementing class, IMO.

**Comment by Ocramius** [comment]
Handled in #330
