### ISSUE TITLE
FindTypeFromAst dropped in #331 with no upgrade path

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#347]
`FindTypeFromAst` was dropped in PR #331 and documented as a BC break (good), but no upgrade path was documented, meaning consumers of this will be left in the dark on how to upgrade their code. It would be helpful to let people know what the best way to handle this BC break is.

**Comment by Ocramius** [comment]
On it.

**Comment by Ocramius** [comment]
@asgrim I documented this in https://github.com/Roave/BetterReflection/pull/348 for now.

**Comment by Ocramius** [comment]
The documented bit is at https://github.com/Roave/BetterReflection/blob/5190d83a4e247451bba78d441bba99d123aade90/UPGRADE.md#betterreflectiontypesfinderfindtypefromast-was-removed

@asgrim I didn't provide a migration path, but we can build an equivalent API, if given the spec.

**Comment by asgrim** [comment]
Just got to reviewing the PR, left some comments as it's already merged: https://github.com/Roave/BetterReflection/pull/348#pullrequestreview-60515560

**Comment by asgrim** [comment]
Resolved with #348.
