### ISSUE TITLE
Investigate PHP 7 compatibility

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#35]
How do we fare in PHP 7? Particularly interesting things at the moment:

* ~~PHP7's AST ext (may require significant rewrites, also loses PHP 5 compat...)~~ probably not, requires an ext currently
* How does `ReflectionParameter` fare when dealing with STHs (e.g. `int`, `string` etc.) - I believe this should "just work"?
* Can we grab the RTH from methods using PhpParser? (Need to check PHP7 compat of that) - then we can implement this alongside #10

**Comment by Ocramius** [comment]
Already implemented from an AST perspective.

**Comment by asgrim** [comment]
Need to implement the following for PHP 7 types:

* [ ] New `ReflectionType` class - see http://php.net/manual/en/class.reflectiontype.php
* [ ] `ReflectionParameter::getType` (should return a `ReflectionType`) - see http://php.net/manual/en/reflectionparameter.gettype.php
* [ ] `ReflectionParameter::hasType` - see http://php.net/manual/en/reflectionparameter.hastype.php
* [ ] `ReflectionFunctionAbstract::getReturnType` (should return a `ReflectionType`) - see http://php.net/manual/en/reflectionfunctionabstract.getreturntype.php
* [ ] `ReflectionFunctionAbstract::hasReturnType` - see http://php.net/manual/en/reflectionfunctionabstract.hasreturntype.php

There's also `ReflectionGenerator` which I've created a separate issue for (see #163)
