### ISSUE TITLE
ReflectionClass::implementsInterface() stopped working

### ISSUE THREAD

**Issue by TomasVotruba** [Roave/BetterReflection#351]
I've updated ApiGen in PR to https://github.com/Roave/BetterReflection/commit/d9b54df

and `ReflectionClass::implementsInterface()`  stopped working: https://github.com/ApiGen/ApiGen/commit/3900a157112055e74f75247a28842a545d8130ed#diff-0214ee96e9f9cff8ab265c3c267a2ad4R162

We detect Exceptions by checking `Throwable` is implemented.  Before array with `Throwable` was returned from this method. Now it's empty.

Any clue what happened?

**Comment by Ocramius** [comment]
@TomasVotruba no clue for now. Is the interface checking specifically broken for `Throwable` or in general?

**Comment by TomasVotruba** [comment]
@Ocramius Well it returns no interfaces at the moment and it did before (tests were passing). So I'd say it's broken in general.

I'll try to isolate the use case.

**Comment by Ocramius** [comment]
@TomasVotruba a minimal test case would help a lot, thanks! :+1:

**Comment by Ocramius** [comment]
@TomasVotruba see https://github.com/Roave/BetterReflection/blob/2aee3b435b4c068fedc4e5f079aa4b8a75faeaa1/test/unit/Reflection/ReflectionClassTest.php#L1069-L1083

The test you want is probably to be designed against the default source locators though.

**Comment by TomasVotruba** [comment]
Thanks!

> The test you want is probably to be designed against the default source locators though.

What does it actually mean?

We use this set of locators, all at once with directories and files as input argument:

- https://github.com/ApiGen/ApiGen/blob/performance/packages/BetterReflection/src/SourceLocator/DirectorySourceLocatorFactory.php
- https://github.com/ApiGen/ApiGen/blob/performance/packages/BetterReflection/src/SourceLocator/FallbackSourceLocatorFactory.php
- https://github.com/ApiGen/ApiGen/blob/performance/packages/BetterReflection/src/SourceLocator/FileSourceLocatorFactory.php
- https://github.com/ApiGen/ApiGen/blob/performance/packages/BetterReflection/src/SourceLocator/ProjectVendorSourceLocatorFactory.php

**Comment by Ocramius** [comment]
Is this one considering internal classes?

https://github.com/ApiGen/ApiGen/blob/560040f3657d9990f92ee3bb6d2932d69417e516/packages/BetterReflection/src/SourceLocator/DirectorySourceLocatorFactory.php#L35-L36

**Comment by TomasVotruba** [comment]
Internal source locator is added here: https://github.com/ApiGen/ApiGen/blob/560040f3657d9990f92ee3bb6d2932d69417e516/packages/BetterReflection/src/SourceLocator/FallbackSourceLocatorFactory.php#L38

**Comment by TomasVotruba** [comment]
I might have a clue! When I call `ReflectionClass::getInheritanceClassHierarchy()` I get parent class `Exception` that is in `InternalLocatedSource`. It doesn't implement `Throwable` though.

![image](https://user-images.githubusercontent.com/924196/30034102-73f38ab2-919f-11e7-93c5-a2363a94e4eb.png)

**Comment by Ocramius** [comment]
I wrote a minimal test to reproduce this, and it fails indeed:

```php

    public function testImplementsInterfaceWithThrowable() : void
    {
        $throwable = (new BetterReflection())->classReflector()->reflect(\Throwable::class);
        $exception = (new BetterReflection())->classReflector()->reflect(\Exception::class);
        $typeError = (new BetterReflection())->classReflector()->reflect(\TypeError::class);

        self::assertTrue($throwable->isInterface());
        self::assertTrue($exception->implementsInterface(\Throwable::class));
        self::assertFalse($exception->implementsInterface(\Iterator::class));
        self::assertTrue($typeError->implementsInterface(\Throwable::class));
        self::assertFalse($typeError->implementsInterface(\Iterator::class));
    }
```

**Comment by Ocramius** [comment]
Bleh, the stub for the `Exception` class was out of sync. Sending patch and adding tests for it right now.

**Comment by TomasVotruba** [comment]
Thank you, I spend over 1 hour over this just wondering.

But how is it possible that it worked before?

**Comment by Ocramius** [comment]
@TomasVotruba https://github.com/Roave/BetterReflection/pull/353

The reason why it was working before is that we used a much more hacky approach, in which we did a `\ReflectionClass -> Zend\Code -> .stub -> BetterReflection\ReflectionClass`.

Now we simply have `.stub -> BetterReflection\ReflectionClass`. The reason is that default parameter values for internal classes cannot be reflected.

**Comment by TomasVotruba** [comment]
I see, thanks for explaining.

**Comment by Ocramius** [comment]
@TomasVotruba give it another shot now :+1:
