### ISSUE TITLE
Uncaught Error: Class PhpParserLocator

### ISSUE THREAD

**Issue by ITPrism** [Roave/BetterReflection#365]
Fatal error: Uncaught Error: Class 'Roave\BetterReflection\SourceLocator\Ast\PhpParserLocator' not found in .../_apigen_kernel_cache/DependencyInjectionDevDebugProjectContainer.php on line 1451

**Comment by Ocramius** [comment]
That's probably just your container compiled with a too old version of BetterReflection

**Comment by ITPrism** [comment]
I see. Thank you!

I use latest **dev-master** releases of BetterReflection and [ApiGen](https://github.com/ApiGen/ApiGen/commits/master).

I am trying to generate PHP Documentation.
I am going to write about this issue to ApiGen.

**Comment by Ocramius** [comment]
Closing as `invalid` here: we will release `2.0.0` very soon, but please don't directly use `dev-master` unless you are prepared for a bumpy-road-experience.
