### ISSUE TITLE
Incorrect PHP version constraint

### ISSUE THREAD

**Issue by nikic** [Roave/BetterReflection#376]
https://github.com/Roave/BetterReflection/blob/master/composer.json#L6 uses `>7.1.0` instead of `>=7.1.0`. Looking at commit history, this does not seem to be intentional.

**Comment by Ocramius** [comment]
Given that there are already multiple new releases, is this worth fixing?

**Comment by TomasVotruba** [comment]
Sure, anyone with PHP 7.1.0 is unable to use it for no technical reason.

**Comment by Ocramius** [comment]
Tbh, I'd rather restrict to newer 7.1.x versions that we tested against. I personally bump all dependencies as I go forward, making the supported range smaller and smaller at each release (it expands automatically anyway, as new releases appear).

That said, I'll still merge #377 😜

**Comment by TomasVotruba** [comment]
:+1: 

7.2 bump comming in December? ;)

**Comment by Ocramius** [comment]
@TomasVotruba why not? Depends if there are new features added to this library.
