### ISSUE TITLE
TypeError: ReflectionFunctionAbstract::getBodyAst() returns null for empty body

### ISSUE THREAD

**Issue by codeliner** [Roave/BetterReflection#378]
Got following error for an empty method body: 

`TypeError: Return value of Roave\BetterReflection\Reflection\ReflectionFunctionAbstract::getBodyAst() must be of the type array, null returned`

[PhpParser\Node\Stmt\ClassMethod](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Stmt/ClassMethod.php#L20) says `stmts` prop is always an array but seems not to be the case.

I'll check if I can provide a bugfix PR to php-parser repo. 
Just wanted to let you know about the bug. Tell me if I should provide a failing test + PR for BetterReflection, too.

**Comment by Ocramius** [comment]
If the bug is with PHP-Parser then it probably should only be cascaded here
if it can't be fixed on that side.

**Comment by codeliner** [comment]
Looks like it is wanted behavior: https://github.com/nikic/PHP-Parser/commit/73dc35cbbd8dd464cedbe83b9cd9c6e1d1ebf144
and https://github.com/nikic/PHP-Parser/issues/235#issuecomment-194505139
/cc @nikic

I'll submit a PR (and a small one for php-parser to update doc block of property)

**Comment by Ocramius** [comment]
That would be sufficient to make phpstan crash in this project, leading to
test+fix on our side
