### ISSUE TITLE
Create ReflectionFunctions/ReflectionClasses from internal definitions

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#38]
We currently can't create `ReflectionFunction`s and `ReflectionClass`es from internal functions/class, as the source code is not available. The only way I see is to use the core reflection API, which is a bit of a fudge, and would rely on #36 anyway (would it even be possible to get type hints? maybe not)

_Todo_
- [x] Internal classes (see #80)
- [x] Internal functions

**Comment by asgrim** [comment]
Possible solution: add a "stub" file we can "reflect" stuff

**Comment by Ocramius** [comment]
Not yet fixed. Frikken functions r missing.

**Comment by Ocramius** [comment]
@asgrim I won't have time for this issue in the near future: shall we delay it?

**Comment by asgrim** [comment]
happy to delay til "1.1.0" milestone

**Comment by asgrim** [comment]
Hmm yes, looks like it has potential & be useful, but hasn't been updated for ~4 years... ideally we need scalar type hints in as well at this stage (can even backport if someone is using PHP 5 so no problem there)

**Comment by Ocramius** [comment]
Yeah, we need some sort of reliable script that keeps stubs in sync...

**Comment by ondrejmirtes** [comment]
We could read `@deprecated` from the phpstorm-stubs.

**Comment by kukulich** [comment]
It looks this could be closed already :)

**Comment by ondrejmirtes** [comment]
We're discussing it in https://github.com/phpstan/phpstan-deprecation-rules/issues/24

**Comment by kukulich** [comment]
It can probably be part of https://github.com/Roave/BetterReflection/issues/603

**Comment by ondrejmirtes** [comment]
Yeah, it probably should be because the stubber will know about the PHP version to check against.

**Comment by Ocramius** [comment]
Closing this: implemented since a while, but I'll mark `4.8.0` as the milestone, since most of the convo revolves around `@deprecated` now.
