### ISSUE TITLE
Question: how to reflect classes that are not in the scope of the located source(s)

### ISSUE THREAD

**Issue by afoeder** [Roave/BetterReflection#383]
My use case is as following, literally copied from the examples:

```
$astLocator = (new BetterReflection())->astLocator();
$directoriesSourceLocator = new DirectoriesSourceLocator([__DIR__.'/../src/Foo/Bar'], $astLocator);
$reflector = new ClassReflector($directoriesSourceLocator);
$classes = $reflector->getAllClasses();

foreach ($classes as $class) {
    $class->getInterfaces();
}
```

The last one throws an error like
> Uncaught Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: Roave\BetterReflection\Reflection\ReflectionClass "Acme\Tests\Foo\BarUnitTest" could not be found in the located source in …/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:33

One of the `$classes` do inherit from the mentioned `…BarUnitTest`, but, that's my assumption, because that one is out of the scope of  `[__DIR__.'/../src/Foo/Bar']` from the SourceLocator and BetterReflection does not autoload, the error is thrown.
How would I face this?

What I'm currently up to is to make the Source locator scope broader and array_filter only the ones I'm interested in. That's a bit more overhead in scanning but that's OK in that case I'd say.

WDYT? And sorry if this issue tracker is not the right place to ask questions…

**Comment by Ocramius** [comment]
If any used symbol comes from outside the source locator scope, this
library will consider it as non-existing.  Broadening the source locator
scope is the correct approach here.

**Comment by afoeder** [comment]
Thank you; for the record since I also had to find that out; the `\Roave\BetterReflection\SourceLocator\Type\AggregateSourceLocator` along providing multiple directories in the DirectoriesSourceLocator did the trick. I'd be able to e.g.

```php
$astLocator = (new BetterReflection())->astLocator();
$directoriesSourceLocator =
    new AggregateSourceLocator([
        new PhpInternalSourceLocator($astLocator),
        new SingleFileSourceLocator(__DIR__.'/../src/Baz/Bar.php', $astLocator),
        new DirectoriesSourceLocator([
            __DIR__.'/../src/Foo',
            __DIR__.'/../src/Bar'
        ], $astLocator)
    ]);
```
