### ISSUE TITLE
AutoloadSourceLocator uses the wrong directory

### ISSUE THREAD

**Issue by oqq** [Roave/BetterReflection#384]
Hi!

In another library using this package an issue appeared which arises from here.
https://github.com/prooph/message-flow-analyzer/issues/2

After some investigation i can summarize it to below facts.

Given my vendor directory, fulfilled from composer, has two packages with the same namespace, but different directories in which the code lies by using PSR-4.
e.g.
- zendframework/zend-expressive-router
- zendframework/zend-expressive-fastroute

And i use composers autoloader and he reckons to uses first the fastroute package and router afterwards. (Was the case in the linked issue)

Than this call
```php
use Roave\BetterReflection\Reflection\ReflectionClass;
$reflection = ReflectionClass::createFromName(\Zend\Expressive\Router\RouterInterface::class);
```

would raise this exception:
```
PHP Fatal error:  Uncaught Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: Roave\BetterReflection\Reflection\ReflectionClass "Zend\Expressive\Router\RouterInterface" could not be found in the located source 
```

The method `attemptAutoloadForIdentifier` returns this file path:
```
vendor/composer/../zendframework/zend-expressive-fastroute/src/RouterInterface.php
```
which is properly wrong and should be:
```
vendor/composer/../zendframework/zend-expressive-router/src/RouterInterface.php
```

This only happens if the `$prefixDirsPsr4` array from `vendor/composer/autoload_static.php` contains a like this:
```php
        'Zend\\Expressive\\Router\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-expressive-fastroute/src',
            1 => __DIR__ . '/..' . '/zendframework/zend-expressive-router/src',
        ),
```

But not if the router is the first value in that array.

Perhaps this is an issue from composer, but since the nativ reflection from php under same circumstances works like a charm, I would drop it here. sorry ;)

```php
$reflection = new \ReflectionClass(\Zend\Expressive\Router\RouterInterface::class);
echo $reflection->getFileName(); #vendor/zendframework/zend-expressive-router/src/RouterInterface.php
```

Thanks!

**Comment by asgrim** [comment]
Interesting find; that kinda makes sense; when we hijack the file stream in https://github.com/Roave/BetterReflection/blob/master/src/SourceLocator/Type/AutoloadSourceLocator.php#L173 we don't actually check the file exists and is valid. Would be fairly simple to implement that tho, I'd think.

**Comment by Ocramius** [comment]
Just adding some spice here (for anyone willing to write test cases): file might be valid and readable, but it may not contain the class.
