### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by mikeSimonson** [Roave/BetterReflection#385]
Hi,

I am trying to use better reflection to reflect on a set of file in various different project.
I try to determine if classes that are in a file extends a specific class, namely TestCase.

Then based on that I want to override some stuff in thoses classes (often the file that contains the class that extends TestCase also contains some fixture class). This means that I don't know the name of the class I need to reflect on.

For now I use

```
        $classLoader = require __DIR__ . '/../../vendor/autoload.php';
        $astLocator = (new BetterReflection())->astLocator();
        $fileSourceLocator = new SingleFileSourceLocator(__DIR__ . $filePath, $astLocator);
        $composerSourceLocator = new ComposerSourceLocator($classLoader, $astLocator);
        $aggregateSourceLocator = new AggregateSourceLocator([
            $fileSourceLocator,
            $composerSourceLocator,
            new PhpInternalSourceLocator($astLocator),
        ]);

        $reflector = new ClassReflector($aggregateSourceLocator);
        $classes = $reflector->getAllClasses();
```

Where filePath is the file that I want to inspect. This completely blows up with Identifier not found  ( name of the class that is in the filepath)

Would that be possible with better reflection or not ?
And any idea how to achieve it ?

Thanks

**Comment by Ocramius** [comment]
> This means that I don't know the name of the class I need to reflect on.

Use a simple `SingleFileSourceLocator` and ask the reflector to give you all defined classes. Then you can reflect it afterwards if you use the aggregate source locator.

**Comment by mikeSimonson** [comment]
For wathever reason it wasn't working yesterday but it does perfectly now.
Thanks

**Comment by Ocramius** [comment]
@mikeSimonson heisenbug
