### ISSUE TITLE
Throw ReflectionException when property not found?

### ISSUE THREAD

**Issue by muglug** [Roave/BetterReflection#389]
`Roave\BetterReflection\Reflection\Adapter\ReflectionClass::getProperty` returns a nullable object, but the method it's extending throws an exception if a given property isn't found. Should that behaviour and return type be matched?

```php
$class = new ReflectionClass('ReflectionClass');
$property = $class->getProperty('naame');
var_dump($property);
?>
```

**Comment by Ocramius** [comment]
Yeah, that would probably be more correct: https://3v4l.org/pZqVl

**Comment by kukulich** [comment]
I’ll prepare a PR in next few days.

**Comment by kukulich** [comment]
Fixed in https://github.com/Roave/BetterReflection/pull/391

**Comment by Ocramius** [comment]
Handled in #391
