### ISSUE TITLE
ReflectionClass::isSubclassOf() does not work when StringSourceLocator is used

### ISSUE THREAD

**Issue by sebastianbergmann** [Roave/BetterReflection#390]
This is probably not a an issue (as in: bug) but rather a problem with me using the component.

When I iterate over a list of source files
```php
foreach ($files as $file) {
    $astLocator = (new BetterReflection())->astLocator();
    $reflector  = new ClassReflector(new StringSourceLocator($file->getContents(), $astLocator));

    foreach ($reflector->getAllClasses() as $class) {
        if ($class->isSubclassOf(TestCase::class)) {
            print "*";
        }
    }
}
```
then I run into the following error
```
Uncaught Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: Roave\BetterReflection\Reflection\ReflectionClass "PHPUnit\Framework\TestCase" could not be found in the located source in ...
```
This is, of course, correct as `PHPUnit\Framework\TestCase` is not declared in the code that is passed as a string to `StringSourceLocator`.

I want to find all classes that are sub-classes of `PHPUnit\Framework\TestCase` and are declared in a list of source files. What am I doing wrong?

**Comment by kukulich** [comment]
You can use `AggregateSourceLocator` with `StringSourceLocator` and `SingleFileSourceLocator`. Pass the file with `PHPUnit\Framework\TestCase` to the `SingleFileSourceLocator`. I hope it should work then.

**Comment by sebastianbergmann** [comment]
For my use case, `PHPUnit\Framework\TestCase` either is already loaded or should be autoloaded.

**Comment by sebastianbergmann** [comment]
Sonehow I overlooked `AggregateSourceLocator`. Thanks!

**Comment by asgrim** [comment]
Indeed, this is a "feature", in fact one of the primary features; the library is completely isolated from what classes are loaded (uses AST not internal reflection)... BR will only ever know about classes you tell it about; you can use an Aggregate as above and give it both the SingleFile locator and the Autoload locators (in order) so it looks in the file first, then relies on the registered autoloader to locate the source for classes it depends on

**Comment by sebastianbergmann** [comment]
@asgrim I understand now that this is a feature. And what a great feature it is :-)
