### ISSUE TITLE
ReflectionClass::isSubclassOf inconsistency

### ISSUE THREAD

**Issue by lookyman** [Roave/BetterReflection#396]
```php
$refN = new \ReflectionClass('ArrayObject');
var_dump($refN->isSubclassOf('Traversable')); // true

$refB = (new \Roave\BetterReflection\BetterReflection())->classReflector()->reflect('ArrayObject');
var_dump($refB->isSubclassOf('Traversable')); // false
```

Is this a known issue or a bug? I've tried to search but couldn't find anything..

**Comment by kukulich** [comment]
I think it's a feature :) `isSubclassOf` in BetterReflection checks only parent classes.

However the adapter is compatible with internal reflection: https://github.com/Roave/BetterReflection/commit/e33439338cafa9322db3f4ab35630a3934235704

**Comment by Ocramius** [comment]
@kukulich no, this looks wrong also here...

The only scenarios where this should return `false` are:

 * it is not a child class
 * it is the class itself

From a naming perspective, this one doesn't make sense:

```php
$refB = (new \Roave\BetterReflection\BetterReflection())->classReflector()->reflect('ArrayObject');
var_dump($refB->isSubclassOf('Traversable')); // false
```

**Comment by kukulich** [comment]
@Ocramius I'm not sure if I understand you well. Should `ReflectionClass::isSubclassOf` really check interfaces? Or the current behavior is ok but I only confused you with "checks only parent classes" ?

**Comment by Ocramius** [comment]
Argh, yeah, indeed, it should not.

Thanks @kukulich, I totally missed that.

Maybe good for a next major to enforce passing a `ClassName` VO as parameter?
