### ISSUE TITLE
GetFirstDocComment inconsistency with native reflection

### ISSUE THREAD

**Issue by lookyman** [Roave/BetterReflection#402]
https://github.com/Roave/BetterReflection/blob/aefddb1e5f7dbd6be0e982bd3865a762651b1762/src/Util/GetFirstDocComment.php#L23 returns reformated text, but the native reflection returns it as it is. Is there a reason for it?

**Comment by Ocramius** [comment]
@lookyman what's the entry point you use? There is a difference between retrieving a docblock and a single doc comment

**Comment by lookyman** [comment]
You are right. I was just digging around in tests, and saw [this](https://github.com/Roave/BetterReflection/blob/aefddb1e5f7dbd6be0e982bd3865a762651b1762/test/unit/Reflection/ReflectionPropertyTest.php#L168) line, which looked weird to me.
