### ISSUE TITLE
PHP nightly (currently) has shortened scalar type names

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#413]
It looks like PHP 7.3 (at least, in `nightly` on Travis atm) may be changing the output of `\ReflectionClass::export` to shorten scalar names (e.g. `integer` => `int`, `boolean` => `bool` etc.) - a BC break to watch out for in Better Reflection.

Not sure what the motivation is in this change, but this may cause us /compatibility/ issues in PHP 7.3.

Discovered this working on another project: https://travis-ci.org/phplang/streams2/jobs/357789078#L640

**Comment by kukulich** [comment]
Solved in https://github.com/Roave/BetterReflection/pull/750
