### ISSUE TITLE
Provide ConstantReflector

### ISSUE THREAD

**Issue by MaXal** [Roave/BetterReflection#416]
I would like to collect all global constants in the same way as it's done via ClassReflector or FunctionReflector.

**Comment by asgrim** [comment]
Global variables or constants...? There's some dissonance between the title/description here...

**Comment by MaXal** [comment]
@asgrim Sorry, I meant constants.

**Comment by kukulich** [comment]
https://github.com/Roave/BetterReflection/pull/471

**Comment by kukulich** [comment]
This can be closed :)
