### ISSUE TITLE
Implementing the closures, invoke and invokeArgs in ReflectionMethod

### ISSUE THREAD

**Issue by prisis** [Roave/BetterReflection#426]
Hey :), i would like to make a pr the 2 missing feature.
First im looking for a good idea how to build this, is it the best way to use the EvaledCodeSourceLocator?

**Comment by Ocramius** [comment]
@prisis nothing to do with the `EvaledSourceLocator` :-)

See https://github.com/Roave/BetterReflection/pull/375, which is a similar patch. Also mind the comments there :+1:

**Comment by kukulich** [comment]
This can be closed. Everything is implemented:

https://github.com/Roave/BetterReflection/blob/5.0.x/src/Reflection/Adapter/ReflectionMethod.php#L221
https://github.com/Roave/BetterReflection/blob/5.0.x/src/Reflection/Adapter/ReflectionMethod.php#L237
https://github.com/Roave/BetterReflection/blob/5.0.x/src/Reflection/Adapter/ReflectionMethod.php#L255

**Comment by Ocramius** [comment]
Thanks @kukulich!
