### ISSUE TITLE
Undefined property: Roave\BetterReflection\Reflection\ReflectionClass::$cachedMethods

### ISSUE THREAD

**Issue by jenschude** [Roave/BetterReflection#428]
When adding a method and trying to get the newly added method from the reflected class e.g:

```
    $classInfo = (new BetterReflection())
        ->classReflector()
        ->reflect($className);

     $classInfo->addMethod('get' . ucfirst($fieldName));
     $classInfo->getMethod('get' . ucfirst($fieldName))->setBodyFromString('return $this->get(\'fieldName\');');
```

I get following error:

```
Undefined property: Roave\BetterReflection\Reflection\ReflectionClass::$cachedMethods
BetterReflection/src/Reflection/ReflectionClass.php:289
BetterReflection/src/Reflection/ReflectionClass.php:399
BetterReflection/src/Reflection/ReflectionClass.php:414
BetterReflection/test/unit/Reflection/ReflectionClassTest.php:1551
```

The error can also be reproduced when running the addMethod test in isolation:

`vendor/bin/phpunit --filter=testAddMethod test/unit/Reflection/ReflectionClassTest.php`

Possible fix is to reinitialize the cachedMethods property in the addMethod method of the ReflectionClass

```
    /**
     * Add a new method to the class.
     */
    public function addMethod(string $methodName) : void
    {
        $this->node->stmts[] = new ClassMethod($methodName);
        unset($this->cachedMethods);
        $this->cachedMethods = null;
    }

**Comment by jenschude** [comment]
Btw there are a lot more tests broken when running them in isolation.

**Comment by Ocramius** [comment]
Is there a way to run the tests in complete process isolation each time? Would be interesting to perform a single run with just that.

**Comment by asgrim** [comment]
> Is there a way to run the tests in complete process isolation each time? Would be interesting to perform a single run with just that.

Yep, use the `--process-isolation` flag. Although I haven't had a chance to run it yet, I'd anticipate it would be quite slow :)

**Comment by jenschude** [comment]
Running them at the moment and collection Fatals and Errors. Will open a new issue in some minutes.

**Comment by jenschude** [comment]
See #429

**Comment by kukulich** [comment]
This is fixed in https://github.com/Roave/BetterReflection/commit/256f09282c338d54e95fcb3190eb916bdba144eb
