### ISSUE TITLE
StringSourceLocator doesn't "locate" source, but returns a LocatedSource object

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#43]
Some conceptual "naming" issue that @Ocramius has... `StringSourceLocator` doesn't "locate" source, but still returns a `LocatedSource` object.

Solutions for this would be to either create a `Source` interface that `LocatedSource` and something else (that the `StringSourceLocator` would return) implement, or create an abstract parent.

Just need to clarify naming and intent

For reference, original discussion at https://github.com/Roave/BetterReflection/pull/32#discussion_r34014981

**Comment by asgrim** [comment]
Will be fixed by resolving #123

**Comment by Ocramius** [comment]
Handled in #123
