### ISSUE TITLE
Is there any way to change doc comment of the method?

### ISSUE THREAD

**Issue by funivan** [Roave/BetterReflection#430]
Can not find how to modify/add/delete method doc comment. Thanks for the help.

**Comment by asgrim** [comment]
At the moment, there is no way; thanks for the feature request though :+1:

**Comment by funivan** [comment]
I need this feature and would like to implement it.

**Comment by Ocramius** [comment]
@funivan mutators are currently work-in-progress: see https://github.com/Roave/BetterReflection/pull/339

**Comment by asgrim** [comment]
@Ocramius the mutators are the new API; I'd be ok with adding this in the current consistent way..
