### ISSUE TITLE
Add a source locator that can detect `"autoload"` and `"autoload-dev"` when given a composer schema definition from either a `composer.json` or a `composer.lock`

### ISSUE THREAD

**Issue by Ocramius** [Roave/BetterReflection#442]
Given a `composer.json`-alike array and a `string $sourcesBasePath`

```php
['autoload' => [
    'psr-0' => [/* ... */],
    'psr-4' => [/* ... */],
    'classmap' => [/* ... */],
    'files' => [/* ... */],
    'exclude-from-classmap' => [/* ... */],
]];
```

we can generate a `SourceLocator` instance that closes around it.

**Comment by Ocramius** [comment]
Relevant: https://github.com/Roave/BackwardCompatibilityCheck/pull/97

**Comment by Ocramius** [comment]
After working on https://github.com/Roave/BackwardCompatibilityCheck/pull/97 and https://github.com/Roave/BackwardCompatibilityCheck/pull/102, I noticed a massive performance slowdown in the discovery of symbols by name. This is because `BetterReflection` (by default) iterates over each source locator, asking for known symbols.

If we implement a PSR-0, PSR-4, and generally a `composer.json`-based source locator, we can make the lookups for existing classes direct hits, instead of recursive (directory) iterator operations, hence speeding up the entire process from `O(n)` to `O(1)` when the location of a class is known.

**Comment by Ocramius** [comment]
An example implementation is available at https://github.com/Roave/BackwardCompatibilityCheck/blob/a239f81bdfb8c68b8cf6c064b75bc13d77d789b7/src/LocateSources/LocateSourcesViaComposerJson.php#L63-L96 - it works, but it is slow as heck due to it being an `AggregateSourceLocator` that contains all files in the discovered paths (and therefore iterates over existing files rather than performing direct hits)

**Comment by moufmouf** [comment]
I haven't the time to work on this directly, but just wanted to mention I did something quite similar:

- [thecodingmachine/classname-mapper](https://github.com/thecodingmachine/classname-mapper) => given a composer.json file and a class name will give you the list of possible file paths. With a few changes to read composer.lock instead of composer.json and that should do the trick.
- [thecodingmachine/class-explorer](https://github.com/thecodingmachine/class-explorer/) (WIP): for a given namespace, will scan all file names and return possibles classes (it does not read the files so it is pretty fast, but can return false positives)

**Comment by asgrim** [comment]
@Ocramius does the [`ComposerSourceLocator`](https://github.com/Roave/BetterReflection/blob/3.2.0/src/SourceLocator/Type/ComposerSourceLocator.php#L46) do this anyway...?

```php
$composer = require "vendor/autoload.php';
$locator = new ComposerSourceLoucater($composer, $astLocator);
```

**Comment by Ocramius** [comment]
As discussed in person, the `ComposerSourceLocator` uses an autoloader for that, and that means creating a real `ClassLoader`:

https://github.com/Roave/BetterReflection/blob/f54261a37683f9ce18237d95a4ecc2172fc205f3/src/SourceLocator/Type/ComposerSourceLocator.php#L7

I could probably try using it, but the code is not side-effect-free, sadly:

https://github.com/composer/composer/blob/568081f9b68b9f7191a90d8ff9289913ee6e0be8/src/Composer/Autoload/ClassLoader.php#L335

**Comment by Ocramius** [comment]
Note that following monstrosity won't be implemented for now:

```
    'exclude-from-classmap' => [/* ... */],
```
