### ISSUE TITLE
Can it read a class and make every function without access modifiers to be public and save?

### ISSUE THREAD

**Issue by spidgorny** [Roave/BetterReflection#443]
Can it read a class and make every function without access modifiers to be public and save it back to the original file?

From:

```
class Legacy {
  function a() {}
  function b() {}
}
```

To:

```
class Legacy {
  public function a() {}
  public function b() {}
}
```

**Comment by Ocramius** [comment]
This is more like what you would do with a tool like PHPCS: yes,
BetterReflection probably can do that, but it would also destroy all the
alignment

**Comment by asgrim** [comment]
Indeed, it's possible (and you'd lose formatting unless you carefully configure the unparser: see https://github.com/nikic/PHP-Parser/blob/master/doc/component/Pretty_printing.markdown), but I don't think this is the best tool for the job. I'd look to [phpcs+phpcbf](https://github.com/squizlabs/PHP_CodeSniffer).
