### ISSUE TITLE
Issue when used in conjuction with APIGen

### ISSUE THREAD

**Issue by drupol** [Roave/BetterReflection#446]
Hello,

I would like to use [APIGen](https://github.com/ApiGen/ApiGen) to generate the API documentation of HTMLTag.
I added these lines in composer.json and run composer update.

Then, when I run the command to generate the documentation, it ends up with an issue in this library.

Here's the log... https://pastebin.com/bfHMSEdD

**Comment by Ocramius** [comment]
That's simply a memory issue: re-run with a higher memory limit (like `php -dmemory_limit=4G <the-script>`)

We can't do much about it in here, since the library is designed to (by default) cache symbols in memory aggressively in order to prevent duplicate parsing operations.

**Comment by drupol** [comment]
Ok, will try now.

Thanks for the fast answer! I'm impressed :-)
