### ISSUE TITLE
Fatal error: MomoizingParser not compatible

### ISSUE THREAD

**Issue by gvanbeck** [Roave/BetterReflection#447]
Hello, 

using: 
`$astLocator = (new BetterReflection())->astLocator();`
`$reflector = new ClassReflector(new ComposerSourceLocator($autoload, $astLocator));`

throws a fatal in php 7.2

`Fatal error: Declaration of Roave\BetterReflection\SourceLocator\Ast\Parser\MemoizingParser::parse(string $code, ?PhpParser\ErrorHandler $errorHandler = NULL): ?array must be compatible with PhpParser\Parser::parse($code, ?PhpParser\ErrorHandler $errorHandler = NULL) in /Users/gertvanbeckevoort/Documents/phpassist/vendor/roave/better-reflection/src/SourceLocator/Ast/Parser/MemoizingParser.php on line 17`

**Comment by Ocramius** [comment]
What version of nikic/PHP_parser?

**Comment by Ocramius** [comment]
Closing: no feedback given.
