### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted at ReflectionClass::getParameters();

### ISSUE THREAD

**Issue by eeliu** [Roave/BetterReflection#459]
I am writting a  module. But encountered such error.

``` php
require_once __DIR__. '/../vendor/autoload.php';


$classInfo = (new \Roave\BetterReflection\BetterReflection())
    ->classReflector()
    ->reflect(app\DBcontrol::class);

// Retrieves the AST statements array *within* the method's curly braces
$ast = $classInfo->getMethod('getData2')->getBodyAst();
$php = $classInfo->getMethod('getData2')->getParameters();

print_r($ast);
print_r($php);
```

```
Array
(
    [0] => PhpParser\Node\Stmt\Expression Object
...

Fatal error: Allowed memory size of 134217728 bytes exhausted at /home/Newfile/tmp/php-7.1.1/Zend/zend_smart_str.c:45 (tried to allocate 125833184 bytes) in tests/test_betterReflection.php on line 21

```
Could you help me out !

**Comment by roukmoute** [comment]
Run your command without memory limit like `php -d memory_limit=-1 file.php`

**Comment by asgrim** [comment]
Aye, increasing available memory (or unlimiting as @roukmoute suggested) is likely the correct course of action here.

**Comment by eeliu** [comment]
@asgrim 
This is my cmd
> php test_betterReflection.php

Later I change print_r to var_dump,then all are good. 
BUT, gets a [result.zip](https://github.com/Roave/BetterReflection/files/2801145/result.zip) (76.3 MB (80,109,568 bit))
I don't know why .


Blow is app\DBcontrol::class
``` php
<?php
namespace app;
use Exception;
use PDO;

class DBcontrol
{
    private $servername;//= "dev-test-mysql:3306";
    private $username ;// = "root";
    private $password ;//= "root";
    private $con;
    public function __construct($dburl, $dbname, $dbpasswd)
    {
        $this->password = $dbpasswd;
        $this->username = $dbname;
        $this->servername = $dburl;
    }

    public function connectDb()
    {echo "onbefore";
    try{  $this->con = new PDO("mysql:host=".$this->servername, $this->username,$this->password);}catch (Exception $e){echo "exp";}
    finally{echo "end";}}

    public function getData1()
    {
        $ret = array();
        $sql = 'show databases;';
        foreach ($this->con->query($sql) as $row) {
            $ret[] = $row;
        }
        return $ret;
    }

    /**
     * @param $a
     * @return array
     */
    public function getData2($a)
    {
        $ret = array();
        $sql = 'illegal sql';
        $ret[] = $this->con->query($sql) ;
        return $ret;
    }

}
```

**Comment by Ocramius** [comment]
@eeliu if you think you found an issue, we'd need a test case to reproduce it

**Comment by asgrim** [comment]
@eeliu short version is, you're trying to output an enormous data structure (the AST, and then the parameters which contains AST anyway). Even if you managed to get PHP to output it, your browser would probably crash trying to render that much. Use a step debugger, or try to output specific pieces that you are interested in. Beyond that, not really sure what the use case is. As @Ocramius already mentioned, if there really is an actual bug/problem, a (failing) test case would much better illustrate the issue. Thanks!

**Comment by eeliu** [comment]
I am not sure what getParameters return, just wondering why that is so large, while just ONE paremeter in getData2.

**Comment by asgrim** [comment]
Because a `BetterReflection` property has a lot of metadata to work on attached to it (the AST is invariable enormous for any non-trivial amounts of code), so you're trying to write out masses of information about the code - and not limited to just information about the parameter. It is not designed to be a runtime library, it is a tool for static / built-time wizardry :grin:

**Comment by eeliu** [comment]
Hmm, maybe misuse getParameters, thanks your kindly response !

**Comment by asgrim** [comment]
It's fine; just don't try to dump the whole parameter :wink:
