### ISSUE TITLE
Refactor SourceLocators to no longer depend on CoreReflection

### ISSUE THREAD

**Issue by theofidry** [Roave/BetterReflection#469]
After discussing about this with Marco: the current behaviour of the `PhpInternalSourceLocator` is to get the core `Reflection` class to be able to forward it to its stubber. This is however making it harder to leverage the PHPStorm stubs. As a result, a solution is to change the stubber signature to no longer depend on the `Reflection` class.

<hr/>
Original message:

I'm attempting to determine if a function is internal. `is_countable`, introduced in PHP 7.3.0, should _always_ appear as internal now that BetterReflection (3.4.0+) is using the PHPStorm stubs when configured to do so. However when I'm checking this in PHP 7.2.0, this throws an exception. Indeed, [this](https://github.com/Roave/BetterReflection/blob/master/src/SourceLocator/Type/PhpInternalSourceLocator.php#L110-L112) will return `null` without even checking the stubs.

Is that the expected behaviour?

**Comment by asgrim** [comment]
That's expected, but probably not ideal for your situation I reckon. I'd class this as a bug, as otherwise we have to start considering what version of PHP is being run by the subject, etc.

**Comment by kukulich** [comment]
I'm working on fix/improvement.

**Comment by kukulich** [comment]
You can try and review https://github.com/Roave/BetterReflection/pull/470

**Comment by kukulich** [comment]
Can be closed :)
