### ISSUE TITLE
FindPropertyType could fail when using StringSourceLocator

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#47]
```php
class FindPropertyType
{
    /**
     * Given a property, attempt to find the type of the property
     *
     * @param PropertyNode $node
     * @param ReflectionProperty $reflectionProperty
     * @return Type[]
     */
    public function __invoke(PropertyNode $node, ReflectionProperty $reflectionProperty)
    {
        $contextFactory = new ContextFactory();
        $context = $contextFactory->createFromReflector($reflectionProperty);
```

Currently, the `$contextFactory->createFromReflector` depends on the `$reflectionProperty` returning a filename from which the factory calls `file_get_contents` to tokenize and find the imports. However, with `StringSourceLocator` there is no file, and as such this will fail.

We need to fix this in the same way as #45 has been implemented (to call `createFromNamespace` instead), as we will be able to access the `LocatedSource` (which should always have non-empty valid PHP code to create context from)

**Comment by Ocramius** [comment]
Handled in #52
