### ISSUE TITLE
Get all dependencies from a ReflectionClass object?

### ISSUE THREAD

**Issue by carlosas** [Roave/BetterReflection#484]
I have been checking the docs and the code and I can't find a simple way to get the dependencies of a class.
I'd like to get a list of FQDN classes that the reflected class is using. From the constructor, new instances, static calls, DocBlocks... Is there a simple way to get it from a ReflectionClass object or is it necessary to dive inside the php-parser structure?

**Comment by Ocramius** [comment]
> I have been checking the docs and the code and I can't find a simple way to get the dependencies of a class.

This is not part of the `BetterReflection` API: dependencies inside the code, such as a `new Something()` called inside the body of a method, are completely ignored.

**Comment by Ocramius** [comment]
You may want to check https://github.com/maglnet/ComposerRequireChecker/ meanwhile

**Comment by carlosas** [comment]
Thank you for the rapid response, I'll check 👍
