### ISSUE TITLE
Why is composer.lock present?

### ISSUE THREAD

**Issue by simPod** [Roave/BetterReflection#487]
I always was in belief that `composer.lock` should not be committed to libraries. That library should comply with all versions within constraints defined in `composer.json`. So I wonder why is `composer.lock` present eg. here? Thanks!

**Comment by Ocramius** [comment]
@simPod mostly for stability of some of the testing tools, such as `php_codesniffer`.

CI runs make sure that newest and stable dependencies are also checked: https://github.com/Roave/BetterReflection/blob/f86b8f9bd6b365b4e9521cbd8d5c299ed1929a34/.travis.yml#L7
