### ISSUE TITLE
Question: when reflecting from string, is it possible to specify a fake filename somehow?

### ISSUE THREAD

**Issue by rulatir** [Roave/BetterReflection#499]
When I reflect from string as in https://github.com/Roave/BetterReflection/blob/master/docs/usage.md#loading-a-class-from-a-string , is it possible to somehow specify a "fake" filename so that `$reflectionClass->getFileName()` could be meaningful?

Motivating use case: I handle locating files myself (circumventing BetterReflection's locator) and I load using flysystem's `Filesystem` that isn't rooted at the real filesystem root.

**Comment by Ocramius** [comment]
Maybe you'd want a flysystem-based locator? Implementing a locator is a bit awkward, but feasible in userland.

**Comment by rulatir** [comment]
I'll look into this.

**Comment by rulatir** [comment]
Looks like `Psr0Mapping` and `Psr4Mapping` are ALMOST filesystem-agnostic except for `is_dir()`. Would you accept a PR that wraps those calls in a protected method?

**Comment by rulatir** [comment]
Same for `file_exists` and `file_get_contents` in PsrAutoloaderLocator.

**Comment by Ocramius** [comment]
Those are supposed to stay `final`: let's not design for inheritance, since a FS check can land in any class in here at any time.

**Comment by rulatir** [comment]
I will try my luck with https://github.com/twistor/flysystem-stream-wrapper

**Comment by rulatir** [comment]
The luck was bad. FSW is buggy and seems to have lost its author's attention. And your response is a firm NO to making the logic in `Psr0Mapping`, `Psr4Mapping` and `PsrAutoloaderLocator` reusable?

**Comment by Ocramius** [comment]
They can be used, but not extended, and won't be opened for inheritance. You can copy and adapt the classes: they are well tested, so you can port the tests too.

**Comment by rulatir** [comment]
> They can be used, but not extended, and won't be opened for inheritance. You can copy and adapt the classes: they are well tested, so you can port the tests too.

Sadly I must interpret your response as a firm NO, because interdiction against copypasting code is virtually a religious commandment to me, and I am a proud zealot. Fact: your library is unsuitable for my purpose. Closing the issue.

**Comment by Ocramius** [comment]
> Copypasting code is INFINITELY worse than definalizing a class.

Sorry, but we will just have to agree to disagree: opening a class for inheritance is a massive amount of added complexity, both for consumers and for maintainers.

You can have a look at the BC compliance differences for [open classes](https://github.com/Roave/BackwardCompatibilityCheck/blob/5.0.0/bin/roave-backward-compatibility-check.php#L95-L182) an [final classes](https://github.com/Roave/BackwardCompatibilityCheck/blob/5.0.0/bin/roave-backward-compatibility-check.php#L95-L182).

Further reference at https://ocramius.github.io/blog/when-to-declare-classes-final/
