### ISSUE TITLE
[PHP8] Signature mismatch

### ISSUE THREAD

**Issue by orklah** [Roave/BetterReflection#513]
Hi,

I'm getting an error on my preview CI on PHP8:
`Fatal error: Declaration of _HumbugBoxa750b42bd25b\Roave\BetterReflection\Reflection\Adapter\ReflectionMethod::invoke($object = NULL, $args = NULL) must be compatible with ReflectionMethod::invoke(?object $object = NULL, ...$args) in phar:///home/runner/work/doctrine-typed-results/doctrine-typed-results/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/Reflection/Adapter/ReflectionMethod.php on line 289`

Seems like there are changes in signature in PHP8 that's not compatible with this library. I couldn't find issues or PR on this subject. Is this already known?
If needed, I can try to create a PR to find a signature both compatible with PHP8 and prior but this is a delicate matter and I don't know Reflection at all for now.

**Comment by Ocramius** [comment]
PHP8 is waaaaaaay out of scope for now 😬

**Comment by kukulich** [comment]
@orklah Btw it looks you are using fork https://github.com/ondrejmirtes/BetterReflection/

**Comment by orklah** [comment]
> PHP8 is waaaaaaay out of scope for now 😬

:D Thought you might say that.

> @orklah Btw it looks you are using fork https://github.com/ondrejmirtes/BetterReflection/

Correct, missed that too.

Well I guess I'll close this for now then!
