### ISSUE TITLE
Achieve 100% type coverage with Psalm

### ISSUE THREAD

**Issue by Lctrs** [Roave/BetterReflection#525]
See https://github.com/Roave/BetterReflection/pull/517 for a great explanation of current issues made by the almighty @Ocramius.

**Comment by orklah** [comment]
I tried to look at this.

There are two main sources of mixed type in the library.
- composer.json and installed.json are two big chunks of decoded json that are passed around as mixed[]. It could be handled with this:
`array{name: string, autoload: array{classmap: array<int, string>, files: array<int, string>, psr-4: array<int, string>, psr-0: array<int, string>}}`.
It's a big chunk of doc that have to be repeated 17 times in MakeLocatorFor* Classes but when it's done, it rises the coverage from 98.9751 to 99.2148

- The second is CompileNodeToValue::__invoke, It's a big complicated and recursive method who return mixed. I don't know enough to know what's really going on here, but if this mixed type here could be removed (by actually detailing every possible type), It could then be propagated easily to the rest of the code and rise almost to 100%...

**Comment by kukulich** [comment]
I think that `CompileNodeToValue::__invoke` returns simple types (or array of simple types)

**Comment by orklah** [comment]
> I think that `CompileNodeToValue::__invoke` returns simple types (or array of simple types)

Great! I will update this and see how it goes!

**Comment by orklah** [comment]
Note: https://github.com/vimeo/psalm/pull/2737 This is a new config for the next Psalm release that will allow reading Php-parser's @property notations. When activated, it should bump the type coverage a bit

**Comment by Ocramius** [comment]
Nice! 💪

BTW, what happens if we run with `totallyTyped="true"`?

**Comment by orklah** [comment]
> BTW, what happens if we run with `totallyTyped="true"`?

35 errors / 99.6937% (with patch from PR that was fixed another way)
Some fixed in https://github.com/nikic/PHP-Parser/pull/647
Some due to black magic and closures
Some due to Reflection returning unpredictable values

It could probably still be narrowed but it's tedious work :p

**Comment by Ocramius** [comment]
With 35 errors left, there is a lot of hope \o/

We just can't achieve 100% if we rely on any core API that exposes `mixed`, heh :D

**Comment by Ocramius** [comment]
Closing here: we're already at a good point :)
