### ISSUE TITLE
ReflectionClass::getTraits don't return the same type as native ReflectionClass::getTraits

### ISSUE THREAD

**Issue by orklah** [Roave/BetterReflection#530]
Hi

While working on #525, I documented ReflectionClass::getTraits as returning `list<ReflectionClass>`.

This is deduced by looking at the data source `$this->node->stmts` which is an `array<int, Node\Stmt>` (or even a `list<Node\Stmt>`, not sure yet).

However, the doc of [ReflectionClass::getTraits](https://www.php.net/manual/en/reflectionclass.gettraits.php) (and psalm stubs) describe the return type as:
> an array with trait names in keys and instances of trait's ReflectionClass in values

> `array<string,ReflectionClass>`

I'm not sure what to do about that...

I wanted to add a failing test in a PR but the only place where I've seen a call to getTraits is in a dataProvider that checks that the return is an empty array.

**Comment by Ocramius** [comment]
I guess that's under-tested now... I'd leave it as-is until someone adds testing around `getTraits`

**Comment by orklah** [comment]
The issue is reversed in ReflectionClass::getReflectionConstants. The native object will return a numerically indexed array where the library returns a string indexed array.

Here's an example of native code: https://3v4l.org/t05Dv

**Comment by kukulich** [comment]
I think everything is ok, see https://github.com/Roave/BetterReflection/pull/593

ReflectionClass adapter returns the right types.

**Comment by orklah** [comment]
Yep, these 3 cases were fixed by @Ocramius in https://github.com/Roave/BetterReflection/commit/beca868be431778a5c5da3ee0aa457763d7f20b4

The @psalm-suppress could have been removed at that occasion.
