### ISSUE TITLE
EvaledCodeSourceLocator broken?

### ISSUE THREAD

**Issue by ondrejmirtes** [Roave/BetterReflection#539]
Hi,
the EvaledCodeSourceLocator started working as I expected once I inverted this condition: https://github.com/ondrejmirtes/BetterReflection/commit/e54a3c233cd7bbf225b89c59d7754434602518c6

But it seems really weird to me as it looks like it has some tests, and the build in my fork started failing too. Can you tell me what's going on? :) Thank you.

**Comment by Ocramius** [comment]
Not sure what's being asked: is there a specific test that is wrong then?

**Comment by ondrejmirtes** [comment]
If you look at the code - does the commit make sense to you or not? I’m not able to tell if the current tests are wrong, or if my expectations are wrong, but at first sight it looks like the ternary then/else branches are switched.

**Comment by Ocramius** [comment]
I would say that the eval source locator operates only on non-existing
source files

**Comment by ondrejmirtes** [comment]
Oh, so for my needs, I should probably use AutoloadSourceLocator. Thank you and sorry.
