### ISSUE TITLE
broken CI

### ISSUE THREAD

**Issue by orklah** [Roave/BetterReflection#542]
I don't see how, but it seems that the ci changed lately and it skips a lot of things now.

I couldn't find a commit that could have this effect.

For example, before, when opening Travis, there were a lot of lines, now there is a single execution. Also, the CI time went from 40+ minutes to 2 minutes.

**Comment by Ocramius** [comment]
Can you point to links to previus/current CI runs, please?

**Comment by orklah** [comment]
Yep, sorry.
This is the list for PR
https://travis-ci.org/Roave/BetterReflection/pull_requests?utm_medium=notification&utm_source=github_status
A broken one (today):
https://travis-ci.org/Roave/BetterReflection/builds/651802000?utm_medium=notification&utm_source=github_status
A normal one (5 days ago):
https://travis-ci.org/Roave/BetterReflection/builds/646268668?utm_medium=notification&utm_source=github_status

And the list for builds:
https://travis-ci.org/Roave/BetterReflection/builds?utm_medium=notification&utm_source=github_status
A broken one (5 days ago):
https://travis-ci.org/Roave/BetterReflection/builds/650142039?utm_medium=notification&utm_source=github_status
A normal one (17 days ago): 
https://travis-ci.org/Roave/BetterReflection/builds/644744328?utm_medium=notification&utm_source=github_status

**Comment by Ocramius** [comment]
Oh wow, I wonder if the travis DSL changed *again* :S

**Comment by orklah** [comment]
What's a DSL?

It seems to be an issue with travis indeed:
https://travis-ci.org/Roave/BetterReflection/jobs/650142040/config?utm_medium=notification&utm_source=github_status
https://travis-ci.org/Roave/BetterReflection/builds/644744328/config?utm_medium=notification&utm_source=github_status
On the bottom of the page, there is a "Build config" frame which is nearly empty on broken executions

**Comment by Ocramius** [comment]
Seems like it isn't picking up anything in the build matrix: defaults to PHP 7.2 due to no configured version 🤔

**Comment by orklah** [comment]
Well, I'm an absolute newb with CI matrix. I won't be able to help much :(

**Comment by kukulich** [comment]
https://travis-ci.org/Roave/BetterReflection/jobs/652195892/config

**Comment by Ocramius** [comment]
I wonder if the windows build is interfering...

**Comment by kukulich** [comment]
root: both matrix and jobs given, matrix overwrites jobs

So it can be probably solved by removing the matrix section

**Comment by Ocramius** [comment]
Yeah, I would also say that 7.4 failures aren't allowed anyway
