### ISSUE TITLE
PhpStormStubsSourceStubber encounters CouldNotFindPhpStormStubs exception when packaged in a phar

### ISSUE THREAD

**Issue by michaeljoelphillips** [Roave/BetterReflection#550]
I've been working on a project that gets packaged as a PHP Archive and depends on Better Reflection.  Recently I noticed some strange behavior with the `PhpStormStubsSourceStubber` depending on how the phar is built.  I've created a [repro case](https://github.com/michaeljoelphillips/br-phar-repro) to demonstrate.

The core issue is that the stubs directory cannot be located because [`is_dir` returns false](https://github.com/Roave/BetterReflection/blob/3.5.0/src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php#L38) when the [phar is built using an iterator](https://www.php.net/manual/en/phar.buildfromiterator.php), causing the `CouldNotFindPhpStormStubs` exception to be thrown.

Originally, I suspected that this behavior was caused by the phar stream wrapper not fully implementing `is_dir`, so I opened #541 to give clients the option of providing the absolute path to the stubber, avoiding the call to `is_dir` altogether.  This wasn't a perfect solution, as it defers errors if the directory doesn't exist.  In creating the repro case however, I accidentally discovered that it seems to only be a problem when the phar is built from an iterator instead of [from a directory](https://www.php.net/manual/en/phar.buildfromdirectory.php).

I think #541 can be closed since the core problem lies elsewhere and I can work around it with how I build the phar, but I thought I would share insight for anyone else that encounters similar problems.

**Comment by Ocramius** [comment]
Yes, anything relying on PHP-core's filesystem stuff (`realpath`, `is_dir`, `is_file`, ...) breaks spectacularly with PHARs. I think you will need a specialized source locator that mounts the phar as a virtual filesystem.
