### ISSUE TITLE
`ReflectionClass` `getConstructor` fails to resolve contstructor

### ISSUE THREAD

**Issue by ecornelisse** [Roave/BetterReflection#557]
The following code is being used to fetch the constructor

```php
        $constructors = array_filter($this->getMethods(), static function (ReflectionMethod $method) : bool {
            return $method->isConstructor();
        });

        if (! isset($constructors[0])) {
            throw new OutOfBoundsException('Could not find method: __construct');
        }

        return $constructors[0];
```
array_filter will preserve arrays keys. Now what happens when the constructor is not the first method? It will have a key greater than 0 and you will always get the exception because its hardcoded looking for key 0...

I suggest the following change to fix this:

```php
        $constructors = array_filter($this->getMethods(), static function (ReflectionMethod $method) : bool {
            return $method->isConstructor();
        });

        if (count($constructors) === 0) {
            throw new OutOfBoundsException('Could not find method: __construct');
        }

        return reset($constructors);
```

**Comment by Ocramius** [comment]
Hey, can you check if this is already fixed by https://github.com/Roave/BetterReflection/pull/523 ?

**Comment by ecornelisse** [comment]
its fixed by that although i would still prefer a cheap reset call over an array_values call. It was fixed a while ago but its still not released? Cant i be released as a hotfix maybe since stuff is breaking? Or is it released in 4.0?

**Comment by Ocramius** [comment]
It's already part of `4.0.0`

**Comment by ecornelisse** [comment]
ok thanks il close this now
