### ISSUE TITLE
Using a class reflector based on composer.json won't load interfaces

### ISSUE THREAD

**Issue by WyriHaximus** [Roave/BetterReflection#562]
Been working on a composer plugin that runs before dumping the autoloader so the normal autoloader isn't available. With some advise from @asgrim and @Ocramius they suggested the following:

```php
(new ClassReflector((new MakeLocatorForComposerJson())(dirname($vendorDir), (new BetterReflection())->astLocator())))->getAllClasses()
```

To get all classes and iterate over them so see which ones implement a specific interface. Now when doing so I'm getting errors about missing interfaces:

```
"Psr\EventDispatcher\ListenerProviderInterface" could not be found in the located source
"Composer\Plugin\PluginInterface" could not be found in the located source
"Psr\EventDispatcher\ListenerProviderInterface" could not be found in the located source
"Psr\EventDispatcher\EventDispatcherInterface" could not be found in the located source
"Psr\Log\LoggerInterface" could not be found in the located source
```

Refs: https://twitter.com/Ocramius/status/1250751832944672768

**Comment by Ocramius** [comment]
> "Composer\Plugin\PluginInterface" could not be found in the located source

This one seems like a valid/expected crash, since `PluginInterface` is only available during `composer` command execution, or when requiring `composer/composer`.

 > Psr\EventDispatcher\ListenerProviderInterface

Seems strictly relate with https://github.com/Roave/BetterReflection/issues/551

**Comment by WyriHaximus** [comment]
> > "Composer\Plugin\PluginInterface" could not be found in the located source
> 
> This one seems like a valid/expected crash, since `PluginInterface` is only available during `composer` command execution, or when requiring `composer/composer`.

Yup, especially since I've been testing with a `composer run-script`, will test it with a `composer install/update` to see if it works as intended.

> > "Psr\EventDispatcher\ListenerProviderInterface" could not be found in the located source
> 
> Seems strictly relate with #551

Doh :woman_facepalming: . Doing these kind of things tends to show you all kinds of shit in all kinds of packages :joy: . Will take it up inside the FIG

**Comment by WyriHaximus** [comment]
Got it to work with a `goto` using `MakeLocatorForComposerJsonAndInstalledJson`, can drop the `goto` when https://github.com/doctrine/coding-standard/pull/176 gets merged and tagged :tada: . Turns out you need the installed to get the rest of your dependencies 😂 .
