### ISSUE TITLE
Add accessors to UnableToCompileNode exception

### ISSUE THREAD

**Issue by localheinz** [Roave/BetterReflection#569]
For a project @mstaab and I are working on it would be useful if we could fetch the name of a constant when an `Roave\BetterReflection\NodeCompiler\Exception\UnableToCompileNode` exception is thrown:

https://github.com/Roave/BetterReflection/blob/0095a8df72ff99e1b785418e97688ff259108694/src/NodeCompiler/Exception/UnableToCompileNode.php#L44-L54

Currently we use a regular expression to analyze the exception message, retrieve the name of the constant, then define the constant, and retry the operation. 

Before I open a pull request, I wanted to inquire if you were open for 

- adding accessors to `UnableToCompileNode`
- extracting dedicated exceptions extending `UnableToCompileNode` (for backwards compatibility) and adding accessors there

What do you think?

**Comment by Ocramius** [comment]
Seems OK to me, although the final aim is to not have an exception of such
type appearing at all 🤔

**Comment by localheinz** [comment]
@Ocramius 

I am not at liberty to share details, but: it's a legacy application!

🤓

**Comment by Ocramius** [comment]
No problem with adding a public read-only property to the exception
