### ISSUE TITLE
Trait method aliases broken

### ISSUE THREAD

**Issue by ondrejmirtes** [Roave/BetterReflection#577]
Hi,
consider this example: https://3v4l.org/a2hQf

Two observations from that:

1) Aliased trait method fetched on another trait should have the aliased name, not the original name.
2) Class that uses a trait with an aliased method should also know the aliased method.

Unfortunately, BetterReflection breaks both of those assumptions. Here's a reproducing example: https://gist.github.com/ondrejmirtes/a8481b8e03880aebd4e0bae5c6d87e86

**Comment by ondrejmirtes** [comment]
Changing 1) might be a BC break, but at least the `Adapter` namespace should get it right, meaning the same behaviour PHP has.

**Comment by kukulich** [comment]
@ondrejmirtes Tests this please: https://github.com/kukulich/BetterReflection/commit/8bb62080fb697831e33a220b353fb5ab1ea9a3cb

**Comment by ondrejmirtes** [comment]
@kukulich Three tests fixed! :) A couple more problems:

1) https://gist.github.com/ondrejmirtes/074f83f77c0a34207a652ab920728062
2) https://gist.github.com/ondrejmirtes/ee84db996e252ffc9c1eefe3e8683a19 (runtime proof: https://3v4l.org/Lj2ab)

**Comment by ondrejmirtes** [comment]
Current version of https://github.com/kukulich/BetterReflection/tree/traits works great! 👍
