### ISSUE TITLE
Access to list of PHP built-in code units

### ISSUE THREAD

**Issue by sebastianbergmann** [Roave/BetterReflection#580]
I am looking for a way to iterate over all PHP built-in functions and classes.

**Comment by ondrejmirtes** [comment]
What is your definition of built-in? Do you mean what's currently available on your system, or basically iterating over all PhpStorm stubs, or something between?

FWIW source locators have `locateIdentifiersByType` which should give you all available identifiers so I'd look into that first if I were you.

**Comment by sebastianbergmann** [comment]
Sorry for not being clear: I would like to iterate over all PhpStorm stubs.

**Comment by kukulich** [comment]
`JetBrains\PHPStormStub\PhpStormStubsMap` has public constants `CLASSES`, `FUNCTIONS`, `CONSTANTS`.

You can iterate them and use `PhpInternalSourceLocator` then.

**Comment by sebastianbergmann** [comment]
@kukulich I'll give that a try, thanks.

**Comment by Ocramius** [comment]
@sebastianbergmann did it work with the `PhpInternalSourceLocator` then?

**Comment by sebastianbergmann** [comment]
I did not have time yet to try it out. But I understand the comments as "it is possible" and "this is how" so I saw no reason to keep this open.
