### ISSUE TITLE
`ReflectionClass::hasMethod()`, `getMethod()` etc should be case insensitive

### ISSUE THREAD

**Issue by kukulich** [Roave/BetterReflection#588]
Only adapter is case insensitive now but there are strange bugs like https://github.com/Roave/BetterReflection/compare/master...kukulich:case-insensitive-methods (it returns two methods now).

I can prepare PR if you agree.

**Comment by Ocramius** [comment]
I think we should also index those maps as `@psalm-var array<lowercase-string, ...>`, since this will keep biting us in many endpoints 🤔
