### ISSUE TITLE
#609 re-introduce PHPStan checking of the `PhpStormStubsSourceStubber` once PHPStan 0.12.26 is out

### ISSUE THREAD

**Issue by Ocramius** [Roave/BetterReflection#620]
See #609 (we need to revert it once upstream is released)

**Comment by kukulich** [comment]
PHPStan 0.12.26 is out but it reports strange errors. Some have to be fixed in other libraries:

- https://github.com/JetBrains/phpstorm-stubs/pull/821
- https://github.com/phpstan/phpdoc-parser/pull/47

**Comment by kukulich** [comment]
Fixed in https://github.com/Roave/BetterReflection/pull/760
