### ISSUE TITLE
Build badge does not work right

### ISSUE THREAD

**Issue by kukulich** [Roave/BetterReflection#631]
Because there’s no Build workflow.

Should the badge be removed or changed eg. to unit tests?

**Comment by Ocramius** [comment]
Hmm, didn't know the badge is related to a specific workflow... Is an
aggregation, or a "depends on" possible, where "build" depends on all other
workflows?

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by kukulich** [comment]
> Is an aggregation, or a "depends on" possible

Probably not: https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

**Comment by Ocramius** [comment]
Eh, guess the badge needs to go then :D

I would probably use the MT one only: that's our most significant scenario.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/
