### ISSUE TITLE
BetterReflection says method Generator::throw() does not exist

### ISSUE THREAD

**Issue by ondrejmirtes** [Roave/BetterReflection#658]
This one is really tricky. The method comes prefixed in the stubs (https://github.com/JetBrains/phpstorm-stubs/blob/b1041ca15222138a1d3d3aa4afb096df215bdc2e/standard/_types.php#L189-L194) because the PHP-Parser couldn't parse the file otherwise - there can't be a userland method called `throw`.

So we can't generate stub data as `public function throw(...`. The question is on which layer this should be fixed. A simple if in ReflectionClass would do but that's ugly. But source locators are all just about source code as string, so we have to patch the AST (modifying the name the ClassMethod node) somewhere...

**Comment by ondrejmirtes** [comment]
I don't know what changed and when, but `public function throw()` is now parsed fine... https://github.com/ondrejmirtes/BetterReflection/commit/45bfa96bdb201734a79067a384a71c8eded9724d

**Comment by ondrejmirtes** [comment]
Looks like it was ever a problem only on PHP 5? https://3v4l.org/u6IhU

**Comment by Ocramius** [comment]
Perhaps it was a bug in an underlying dependency then?

Is there a test case we can introduce to prevent a regression here?

**Comment by ondrejmirtes** [comment]
I think PhpStorm has the prefix because it would confuse their parser. But I think the PHP 7 RFC “context sensitive lexer” solves this. The test is simply that the Generator stub is parsed without a syntax error and that Generator::throw() exists.

**Comment by kukulich** [comment]
Fixed in https://github.com/Roave/BetterReflection/pull/761

**Comment by Ocramius** [comment]
Thanks @kukulich!
