### ISSUE TITLE
Trait method aliases don't work in a simple scenario without insteadof

### ISSUE THREAD

**Issue by ondrejmirtes** [Roave/BetterReflection#659]
See this example:

```php
trait Foo {
	public function bar(): void {

	}
}

class SomeClass {
	use Foo {
		bar as baz;
	}
}
```

BetterReflection reports that `SomeClass::baz()` does not exist.

Additionally, `SomeClass::bar()` also exists and it doesn't seem like a PHP bug. The manual says (https://www.php.net/manual/en/language.oop5.traits.php):

> The Aliased_Talker makes use of the as operator to be able to use B's bigTalk implementation under an additional alias talk. 

Runtime proof: https://3v4l.org/kBjVh
Reproduction: https://gist.github.com/ondrejmirtes/a18fc61b29d2319beb792ec5252b1939

_Silly me 2 days ago thought that https://github.com/Roave/BetterReflection/issues/647 was bad enough 🤦_

**Comment by Ocramius** [comment]
Handled in #652
