### ISSUE TITLE
`ReflectionClass::getImmediateInterfaces` fails on anonymous classes

### ISSUE THREAD

**Issue by smoench** [Roave/BetterReflection#664]
Given I have following code snippet I want to be analyzed:

```php
<?php

use Roave\BetterReflection\BetterReflection;
use Roave\BetterReflection\Reflector\ClassReflector;
use Roave\BetterReflection\SourceLocator\Type\StringSourceLocator;

require_once __DIR__.'/vendor/autoload.php';

$code = <<<PHP
<?php

declare(strict_types=1);

namespace Tests\SensioLabs\Deptrac\AstRunner\Resolver\Fixtures;

interface InterfaceB
{
}

class ClassA
{
    public function foo()
    {
        return new class() implements InterfaceB {
        };
    }
}

PHP;


$reflector = new ClassReflector(new StringSourceLocator($code, (new BetterReflection())->astLocator()));
$reflectionClasses = $reflector->getAllClasses();

print_r(
    array_keys(
        $reflectionClasses[2]->getImmediateInterfaces()
    )
);
```

I would expect `Tests\SensioLabs\Deptrac\AstRunner\Resolver\Fixtures\InterfaceB` will returned.
But got following exception:
<details>
<pre>
PHP Fatal error:  Uncaught Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: Roave\BetterReflection\Reflection\ReflectionClass "Tests\SensioLabs\Deptrac\AstRunner\Resolver\Fixtures\InterfaceB" could not be found in the located source in ***/deptrac/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:29
Stack trace:
#0 ***/deptrac/vendor/roave/better-reflection/src/Reflector/ClassReflector.php(39): Roave\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier(Object(Roave\BetterReflection\Identifier\Identifier))
#1 ***/deptrac/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(972): Roave\BetterReflection\Reflector\ClassReflector->reflect('Tests\\SensioLab...')
#2 ***/deptrac/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(1150): Roave\BetterReflection\Reflection\ReflectionClass->reflectClassForNamedNode(Object(PhpP in ***/deptrac/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 29

Fatal error: Uncaught Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: Roave\BetterReflection\Reflection\ReflectionClass "Tests\SensioLabs\Deptrac\AstRunner\Resolver\Fixtures\InterfaceB" could not be found in the located source in ***/deptrac/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 29

Roave\BetterReflection\Reflector\Exception\IdentifierNotFound: Roave\BetterReflection\Reflection\ReflectionClass "Tests\SensioLabs\Deptrac\AstRunner\Resolver\Fixtures\InterfaceB" could not be found in the located source in ***/deptrac/vendor/roave/better-reflection/src/Reflector/Exception/IdentifierNotFound.php on line 29
</pre>
</details>

**Comment by Ocramius** [comment]
Possibly similar to #505?

**Comment by smoench** [comment]
Well, the exception is caused by https://github.com/Roave/BetterReflection/blob/master/src/Reflection/ReflectionClass.php#L972 but #505 changes only the `ReflectionObject`. Probably the adjustments need also applied on `ReflectionClass`.

**Comment by Ocramius** [comment]
Could you try out the PR branch? I'm intending to look at it later today, hopefully.

**Comment by smoench** [comment]
Yes, will try. No need to hurry. I still evaluating if better-reflection is usable for deptrac. Currently I skipping anonymous classes as it will be analyzed through the body ast of that method. And I still missing where the dependencies are being used (need to open another issue with a better description).

**Comment by smoench** [comment]
I tried out #505 but did not work. So I combined #505 with #665 and my test script worked 🤷
