### ISSUE TITLE
Adapter\ReflectionClass::$name is empty

### ISSUE THREAD

**Issue by ondrejmirtes** [Roave/BetterReflection#673]
It should contain the class name instead.

Not sure if this has a solution, tried something but PHP doesn't allow it: https://3v4l.org/dmV2m

**Comment by ondrejmirtes** [comment]
Reflection doesn't help here: https://3v4l.org/9cOop

**Comment by Ocramius** [comment]
Fear not, for I have seen the gates of hell, and I hath returned! https://3v4l.org/PBRN1

**Comment by ondrejmirtes** [comment]
Awesome, I need to take a shower now 😝  😃

**Comment by powtac** [comment]
$name somehow protected?

**Comment by ondrejmirtes** [comment]
Looking at https://github.com/JetBrains/phpstorm-stubs/blob/master/Reflection/Reflection.php there are 12 such properties.

I sent a fix for the first one: https://github.com/Roave/BetterReflection/pull/674 If the review passes I can send fixes for the rest too.

**Comment by Ocramius** [comment]
Handled in #674
