### ISSUE TITLE
ReflectionClass:getConstants() signature has changed in PHP 8

### ISSUE THREAD

**Issue by TRowbotham** [Roave/BetterReflection#679]
Running PHPStan on PHP 8 gives the following error due to a function signature mismatch for `ReflectionClass:getConstants()`:

```bash
PHP Fatal error:  Declaration of _HumbugBox69342eed62ce\Roave\BetterReflection\Reflection\Adapter\ReflectionClass::getConstants() must be compatible with ReflectionClass::getConstants(int $filter = ReflectionClassConstant::IS_PUBLIC | ReflectionClassConstant::IS_PROTECTED | ReflectionClassConstant::IS_PRIVATE) in phar:///home/travis/build/TRowbotham/punycode/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/Reflection/Adapter/ReflectionClass.php on line 205
```

From the PHP 8 [upgrade notes](https://github.com/php/php-src/blob/php-8.0.0alpha2/UPGRADING):
>- Reflection:
>    ReflectionClass::getConstants and ReflectionClass::getReflectionConstants results
>    can be now filtered via a new parameter `$filter`. 3 new constants were added to
>    be used with it:
>
>      ReflectionClassConstant::IS_PUBLIC
>      ReflectionClassConstant::IS_PROTECTED
>      ReflectionClassConstant::IS_PRIVATE

**Comment by Ocramius** [comment]
Yeah, the library is not yet tested for PHP 8.x, and no work has been started to get there.

I'd expect any efforts to start after the summer is over, and 8.x is completely in feature freeze.

**Comment by ondrejmirtes** [comment]
I already did some work in my fork (it even supports union types and mixed type), so some one can pick up the code and polish it for this main repo :) https://github.com/ondrejmirtes/BetterReflection/commit/0acd4522bd500547cf2574acb3b1a04b177869ae (https://github.com/ondrejmirtes/BetterReflection/commits/master)

**Comment by kukulich** [comment]
I did some work too but currently I'm learning Python 😃

**Comment by Ocramius** [comment]
We can probably fix the crashes, but we still have a loooooot of work to do anyway.

I would suggest making a push once it is safe to do so, or else we just waste a lot of everyone's time 🤷‍♀️

**Comment by kukulich** [comment]
Fixed by https://github.com/Roave/BetterReflection/pull/750

**Comment by kukulich** [comment]
@Ocramius This can be close.
