### ISSUE TITLE
Add getColumn everywhere to complement getStartLine/getEndLine

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#68]
Yep.

Note; probably `getStartColumn` and `getEndColumn` will be implemented

**Comment by asgrim** [comment]
@Ocramius the PHP-Parser lexer doesn't actually have these attributes... https://github.com/nikic/PHP-Parser/blob/master/doc/component/Lexer.markdown#lexer-options is this strictly necessary?

**Comment by Ocramius** [comment]
This will make the reflector crash, remember?

```php
$closure1 = function () {}; $closure2 = function () {};
```

That's the reason for having the columns as well

**Comment by asgrim** [comment]
We can probably do this now actually; but it's not quite as straightforward. There is `startFilePos` and `endFilePos` which tells us which character in the entire file it is. In theory, we could find how many newlines there are up until those points and figure out the number of lines, but without fixing upstream, not sure of a better way ATM.

**Comment by kukulich** [comment]
@Ocramius Can you close this please?

**Comment by Ocramius** [comment]
Handled in #322
