### ISSUE TITLE
Please provide a CHANGELOG in "standard" format

### ISSUE THREAD

**Issue by llaville** [Roave/BetterReflection#680]
Even if there is not yet a standard to keep a changelog file, lot of Open Source Projects have already adopted the https://keepachangelog.com/en/1.0.0/ format.

It will be greatly apprecied to follow changes in this project in this keep a changelog format rather than the `UPGRADE.md` file.

**Comment by Ocramius** [comment]
Deferring to https://github.com/laminas/automatic-releases/issues/5

**Comment by Ocramius** [comment]
Meanwhile, our releases include a changelog @ https://github.com/Roave/BetterReflection/releases (`git tag` also displays that info)
