### ISSUE TITLE
Expose PHP internal stubs map

### ISSUE THREAD

**Issue by carlosas** [Roave/BetterReflection#693]
I have seen that PhpInternalSourceLocator makes the reflector have the references to core+extensions classes, but they are not returned while trying to retrieve all the classes found:
```
$br = new BetterReflection();
$reflector = new ClassReflector(new PhpInternalSourceLocator($br->astLocator(), $br->sourceStubber()));
var_dump($reflector->getAllClasses()); //array(0) {}
```

This makes total sense while it's aggregated to another locator like AutoloadSourceLocator but is there a way to retrieve them?
If not, would be possible to expose (reflected or not) the class-map generated in PhpStormStubsSourceStubber or the PhpStormStubsMap generated by phpstorm-stubs?

**Comment by Ocramius** [comment]
@carlosas could you perhaps make a small example (in code) of what behavior you are expecting? The `SourceStubber` interface does not really allow enumerating existing symbols, since some implementations of it really just generate symbols on-the-fly:

https://github.com/Roave/BetterReflection/blob/5b4d1c53768e2a3bc32ab348752663733fd70546/src/SourceLocator/SourceStubber/ReflectionSourceStubber.php#L72-L79

**Comment by carlosas** [comment]
To be honest I would expect this code to return all the internal classes reflected, but then you would need to find an alternative approach to not aggregate them while using it with another locator (since this is the current behaviour). Maybe let the user choose with some sort of flag?
```
$br = new BetterReflection();
$reflector = new ClassReflector(new PhpInternalSourceLocator($br->astLocator(), $br->sourceStubber()));
var_dump($reflector->getAllClasses());
```

An alternative would be to have some kind of _get known symbols_ in the `SourceStubber` and then stubbers like ReflectionSourceStubber would just have an empty return since they don't know any by themselves.
```
(new PhpInternalSourceLocator($astLocator, $sourceStubber))->getAllKnownSymbols();
```

A second alternative would be having a simple wrapper of PhpStormStubsMap which can return a list of internal classes/functions/constants.
```
(new PhpInternalSymbols())->getClassMap();
(new PhpInternalSymbols())->getFunctionMap();
(new PhpInternalSymbols())->getConstantMap();
```

Probably not the best naming but I think any of the alternatives would work. For my use case right now I just need to know the FQCNs, and I guess once having it, you can create stubs and/or reflect them.

**Comment by Ocramius** [comment]
Thinking further about this, I wonder if this is an X/Y problem.

The design behind locators us around laziness, for both performance reasons and to avoid side-effexts where possible: enumeration is a completely different scope.

So I'm now wondering what the use-case for such APO is, given that in-memory symbols can be enumerated without this library.

**Comment by carlosas** [comment]
> given that in-memory symbols can be enumerated without this library

I'm not sure if you are talking about `\ReflectionExtension` but AFAIK (which is not much) this can be only used for extensions installed in the running system.

I'm using this library in addition to php-parser for a static analysis tool. At some point I need to know if a certain item type is from the core/extensions to treat them differently. Since you are already managing this list in the library, I thought it was quite easy to expose it, but you are right that probably listing them is out of the scope of the library.

**Comment by Ocramius** [comment]
> At some point I need to know if a certain item type is from the core/extensions to treat them differently.

Perhaps it would be information added to a `LocatedSource` then? 🤔

**Comment by carlosas** [comment]
This would work for items that BetterReflection extracts from the AST by itself (parents, method returns, etc). In my case I'm also extracting types from the method body manually, so it wouldn't be possible to check if a certain item from there is internal or not. That's why I suggested an isolated service that would be able to check or return string classnames.

If you think exposing the raw information lowers the cohesion of the tool, it's not a big deal to do it manually.

**Comment by kukulich** [comment]
@carlosas I'm not sure if I understand you correctly but the list is here: https://github.com/JetBrains/phpstorm-stubs/blob/master/PhpStormStubsMap.php

**Comment by Ocramius** [comment]
@carlosas I didn't understand this section:

 >  In my case I'm also extracting types from the method body manually, so it wouldn't be possible to check if a certain item from there is internal or not. 

Given a symbol name, cannot you do a lookup?

Besides that, does @kukulich's feedback address your concerns? That's effectively what we use to reflect internals, **when** a stub is defined

**Comment by carlosas** [comment]
> Given a symbol name, cannot you do a lookup?

That's true. If the information is in the LocatedSource I guess I could create an Identifier and locate it. I'm not sure about the performance of this at big scale, but it seems this might be the correct way to do it.

Regarding PhpStormStubsMap: I mentioned it in the first message because it's what I'm actually using, but I thought there is no need to have this dependency (and maintain it or do fixes) if BetterReflection already does it internally.

**Comment by Ocramius** [comment]
Closing here - discussed, and IMO solved.
