### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by ondrejmirtes** [Roave/BetterReflection#701]
I already did most of these steps [in my fork](https://github.com/ondrejmirtes/BetterReflection) because I want PHPStan to be ready for PHP 8 on day one or sonner.

This is what needs to be done in BetterReflection in order to fully support PHP 8:

- [x] Adapter signatures compatibility (https://github.com/ondrejmirtes/BetterReflection/commit/0acd4522bd500547cf2574acb3b1a04b177869ae)
- [x] `mixed` type (https://github.com/ondrejmirtes/BetterReflection/commit/fabd25923c2a1ec96e3bedbdd09267d88a150f15)
- [x] `static` type (https://github.com/ondrejmirtes/BetterReflection/commit/e6f9b722e8af66566caad705cd541c213bd4d106)
- [x] Reflecting union types (https://github.com/ondrejmirtes/BetterReflection/commit/ce858eba391542639e8d2ea725df27ffaeca4e01 - this commit needs to be broken up because it mixes more things)
- [x] `ReflectionType::__toString` breaking change in PHP 8 - nullable type includes `?` again (https://3v4l.org/CmTA1)
- [x] `ReflectionSourceStubber` misses to generate return types (https://github.com/ondrejmirtes/BetterReflection/commit/6a87721f5c95792d754b30931b283c91897995a6)
- [x]  `isBuiltin()` is supposed to be only on `ReflectionNamedType` in PHP 8 (https://github.com/ondrejmirtes/BetterReflection/commit/86c5ce76560c561209cc36f05d576d0bc761ede0)
- [x] `Stringable` (https://github.com/ondrejmirtes/BetterReflection/commit/e9f99da6586dab440cc4117379fdbdb912a1697e)
- [x] `PhpStormStubsSourceStubberTest` will fail a lot when building on PHP 8 because a lot of stuff changed between PHP 8 and PHP 7
- [x] Promoted properties in constructor - I plan to solve this by making ReflectionProperty an interface with two implementations - one based on `Property` node, the other based on `Param` node.
- [x] Only `__construct` methods can be considered constructors
- [x] Support for reading Attributes
- [x] Constant of value `null` as a default parameter value no longer makes the parameter type nullable

The `Stringable` commit and the obsoleted old-style constructors require an `if` based on the PHP version. I did that with a public static property on `BetterReflection` but a different way can be fine too.

Some of these items require a new major version, but some of them can be done in a minor version before that.

I'm creating this issue because I plan to send PRs for these (in case someone isn't faster than me) but I'd like to hear your opinions first :)

**Comment by Ocramius** [comment]
> I'm creating this issue because I plan to send PRs for these (in case someone isn't faster than me) but I'd like to hear your opinions first :)

I mean, PHP 8 support is certainly to be added, but no work has been done here so far because we're all quite busy with other work at the moment, so I would expect us to be somewhere close to compliance in January or such :D 

If the patches are QA'd properly (reads: tests + acceptable MT) and made separate, they are very welcome! :+1:

**Comment by limingxinleo** [comment]
PHP8.0 was released.

**Comment by ghost** [comment]
please support PHP8, thanks

**Comment by Ocramius** [comment]
As I mentioned above:

 > so I would expect us to be somewhere close to compliance in January or such :D

If you want to help out, send patches for the bullet points that @ondrejmirtes wrote above

**Comment by Ocramius** [comment]
Marking this issue as a blocker for `4.12.0` - we'll try getting PHP 8 support in that version.

**Comment by huangzhhui** [comment]
> Marking this issue as a blocker for `4.12.0` - we'll try getting PHP 8 support in that version.

I notice that `4.12.0` has been released in 16 days ago, any progress about PHP 8 compatibility ?

**Comment by Ocramius** [comment]
@huangzhhui nay: busy with other work, but please send patches, if you can help out.

**Comment by DanielBadura** [comment]
I think the result we are aiming here is to support ^7.4 and ^8.0 or do we want to drop 7.4 support?
Im asking because of the `::export` method from `ReflectionClass`,  `ReflectionFunction` etc. got dropped in 8.0 and this would result in big if/else on `PHP_VERSION_ID` i suppose.

**Comment by Ocramius** [comment]
@DanielBadura at first `^7.4 || ~8.0.0`, and after that only `~8.0.0` in a new minor release: that allows upgrading easily.

**Comment by lisachenko** [comment]
Hello, gentlemen! Are there any ETA on when PHP8 will be supported by BR? @ondrejmirtes maybe you can work on this? Unfortunately, I don't have too much time now to maintain my libraries and `goaop/parser-reflection` is one of them which can be replaced with BR, but if BR won't have PHP8 support soon, I might opt to keep supporting it...

**Comment by Ocramius** [comment]
On my end, I had almost zero time for OSS since December: trying to mostly
fit it when something work-related requires intervention.

The whole COVID situation is a massive deterrent to invest more time than
necessary in OSS, and it will likely stay like this until I'm free to leave
my home again, or else the net result will be a clear computer-related
burnout 😩

Any help in improving the lib is very welcome, and I'll certainly react to
any patches sent (review/merges).

**Comment by lisachenko** [comment]
Thank you @Ocramius! I can completely understand this, no worries.

It is very important to prevent OSS burn out, especially for you, as half of most popular PHP libraries were invented/developed by you, so want just to say thank you for working on all of them 👍 

It's a spring time, so relax a little bit, drink your favourite beer, prepare a BBQ and of course, stay healthy!

PS. There are small chances that I'll have some time for OSS, but want to work more on my own libraries and `laminas-code` package a little bit, preparing changes for the next major version for your review.

**Comment by lanlin** [comment]
```shell
Error : Typed static property Roave\BetterReflection\Reflection\ReflectionFunctionAbstract::$parser must not be accessed before initialization
```

**Comment by shaffe-fr** [comment]
Hi, 
From the list in the first comment, is there a specific task that is delaying PHP 8 support?
I can give it a try to solve it!
Thanks

**Comment by Ocramius** [comment]
@shaffe-fr all tasks need implementing: pick one, start doing it, and we'll get closer to having `"php": "^8"` support.

**Comment by dereuromark** [comment]
We now also switched to https://github.com/ondrejmirtes/BetterReflection/ as it doesn't block PHP8 usage
Works nicely.

**Comment by Ocramius** [comment]
@dereuromark which is sad: now we have to basically backport stuff, instead of actually working collaboratively :-( 

In practice, of all people that pinged here, we've seen very little help/involvement, and a lot of workarounds and hacking around stuff instead of actually "bringing it home", and actually being of aid.

**Comment by DanielBadura** [comment]
It is still on my list. Unfortunatly i had not much time lately :(

**Comment by ondrejmirtes** [comment]
I don't recommend using my fork because I'm interested only in bug reports that manifest in PHPStan. So bugs in functionality that's not used by PHPStan will not be fixed.

I've also removed some functionality from the fork to trim down on dependencies.

**Comment by ondrejmirtes** [comment]
If anyone wants to be of help, they can go through the commits I added in master of my fork, and submit them as separate PRs here.

**Comment by WyriHaximus** [comment]
@ondrejmirtes @Ocramius Any suggestions which to pick up first or can I just spree that master branch as PR per commit?

**Comment by ondrejmirtes** [comment]
@WyriHaximus Maybe read all the commits first so you learn what's going on there, maybe you'll realize some changes should be grouped together 😊

**Comment by WyriHaximus** [comment]
@ondrejmirtes Yeah, and probably also the ones in the checklist of this issue :).

**Comment by kukulich** [comment]
@Ocramius Would be possible to make some branch PHP8 only and do major release when PHP8 support is done? It should be much easier...

**Comment by Ocramius** [comment]
A major release shouldn't be needed, since this is just a dependency change.

In theory, a `^7.4|~8.0.0` release should be attempted to allow for downstream to upgrade.

Are there bits that require a complete cut/BC break?

**Comment by kukulich** [comment]
@Ocramius 

It will be much easier to create PRs. Eg. make `PhpStormStubsSourceStubberTest` to work on PHP 7.4 and PHP 8.0 will be massive pain. 

`::export()` methods are removed on PHP 8, so it would be fine to remove them here too - are useless anyway. And it will be BC break.
https://www.php.net/manual/en/reflectionclass.export.php

There may be other places where "PHP 8 only" can help.

I must say... I'm a little ~pissed of~ unhappy about the state of this issue - people (almost all) just complain and no PR coming... So I decided I'll try to fix the PHP 8 support. I can find some time now (summer is over, children in school - no lockdown currently) but I don't want to do unnecessary work... My time is limited and my willingness to work on open source too :)

**Comment by WyriHaximus** [comment]
> I must say... I'm a little ~pissed of~ unhappy about the state of this issue - people (almost all) just complain and no PR coming... So I decided I'll try to fix the PHP 8 support. I can find some time now (summer is over, children in school - no lockdown currently) but I don't want to do unnecessary work... My time is limited and my willingness to work on open source too :)

Same here @kukulich, how about we use this issue to coordinate the work so we don't do double work and we can all pick up a part as long as we communicate who does what.

**Comment by kukulich** [comment]
@WyriHaximus It would be perfect if we can split the work between us :)

**Comment by Ocramius** [comment]
@kukulich I'd say that a `~8.0.0` (only) release is better than no release at all then: if you think we need to drop compatibility to move forward in any way, then let's do it 👍

**Comment by kukulich** [comment]
@WyriHaximus I'll try to first improve https://github.com/Roave/BetterReflection/pull/750 to make BR run on PHP 8 with updated dependencies.

**Comment by WyriHaximus** [comment]
@kukulich Ok awesome, then let you get that in first before we divide and conquer. Unless there is something I can already start on. Have time reserved for this tomorrow so I'll also get familiar with the code and the changes Ondřej did.

**Comment by kukulich** [comment]
@WyriHaximus I think you can try anything based on my branch. I will try to make the build green as a start.

**Comment by WyriHaximus** [comment]
@kukulich Cool, starting with `ReflectionNamedType::isBuiltin`

**Comment by WyriHaximus** [comment]
Now that I'm working on it, will probably do the named and union type changes in one go for reflection type

**Comment by WyriHaximus** [comment]
@kukulich Build #752 on your work, probably have to rebase it when you're done

**Comment by kukulich** [comment]
These are fixed/implemented in #750 and #752 :

- Reflecting union types
- `ReflectionType::__toString` breaking change in PHP 8
- `ReflectionSourceStubber` misses to generate return types
- `isBuiltin()` is supposed to be only on `ReflectionNamedType`
- `PhpStormStubsSourceStubberTest` will fail a lot
- Constant of value `null` as a default parameter value no longer makes the parameter type nullable

**Comment by kukulich** [comment]
https://github.com/Roave/BetterReflection/pull/759

- Only `__construct` methods can be considered constructors

**Comment by kukulich** [comment]
`Stringable`: https://github.com/Roave/BetterReflection/pull/770

**Comment by kukulich** [comment]
@WyriHaximus Btw I'll try `Promoted properties in constructor` as next.

**Comment by WyriHaximus** [comment]
@kukulich Came across that in a few places already <3

**Comment by Ocramius** [comment]
I think we're only missing:

 * promoted properties
 * attributes

Then we're probably ready to go with `8.0`

**Comment by kukulich** [comment]
Promoted properties: https://github.com/Roave/BetterReflection/pull/785

**Comment by kukulich** [comment]
Attributes: https://github.com/Roave/BetterReflection/pull/787

**Comment by WyriHaximus** [comment]
@Ocramius @kukulich Sorry got side tracked for a few days, is there anything besides attributes that needs to be done?

**Comment by kukulich** [comment]
@WyriHaximus Nope, PHP 8 is “done”. You can try to do something in PHP 8.1 - eg. intersection types :)

**Comment by WyriHaximus** [comment]
@kukulich Looks like a royal pain in the ass, I'm on it

**Comment by kukulich** [comment]
@WyriHaximus you can start here: https://github.com/Roave/BetterReflection/pull/767

**Comment by WyriHaximus** [comment]
@kukulich Cool will rebase it off that one later. So far it looks very similar to the work I've done on the named and union types so this could be a lot easier than I thought.

**Comment by WyriHaximus** [comment]
@Ocramius @kukulich Was just looking at `ReflectionUnionType` and AFAIK union types can't be nested, noir does that make sense. Then shouldn't we just filter out the `ReflectionNamedType`s like this? https://github.com/WyriHaximus-labs/BetterReflection/commit/356777b9e10363b51a6fc1d6e9411e0dec2fdc91#diff-7a5518cccd601dbefec3f22042c8486f69b20ebd3fccabc87bf0f44b9c2cbedf

**Comment by Ocramius** [comment]
#787 is the last bit missing here, but beware that we will only support `php:^8.0.12` onwards.

**Comment by Ocramius** [comment]
Closing here: we'll probably still finish up PHP 8.1 support before releasing, but all the topics in here are pretty much exhausted 👍

**Comment by ondrejmirtes** [comment]
Thank you, I'm really happy about this 😊 I'm probably gonna have to devote November and December to bringing PHP 8.1 support into PHPStan, and this is gonna help me a lot 😊
