### ISSUE TITLE
Misleading exception message

### ISSUE THREAD

**Issue by tomasnorre** [Roave/BetterReflection#714]
After adding #711, the exception message should be correct. I overlooked this as part of my PR before. 

I've just seen that the exception needs to be adjusted. It still contains path-info to vendor/composer/installed.json

https://github.com/Roave/BetterReflection/blob/ecd6c1e0af34df5bc2d94f850f2b37f1dc29b782/src/SourceLocator/Type/Composer/Factory/Exception/MissingInstalledJson.php#L16

It's not critical, but misleading, but I would need to add the vendor-dir to the input variables for the exception otherwise the vendor-dir would be unknown to the function. 

Feel free to assign me and I'll try to cleanup my mess.

**Comment by tomasnorre** [comment]
There are multiple things still off. This is also referring to vendor-folder hardcoded. Will see that I get it all fixed

https://github.com/Roave/BetterReflection/blob/ecd6c1e0af34df5bc2d94f850f2b37f1dc29b782/src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php#L40

**Comment by Ocramius** [comment]
I replaced the URIs with absolute ones (use the `Y` shortcut to generate those on github/gitlab :-) )

**Comment by tomasnorre** [comment]
Will see when I find the time to clean up the rest. I have some changes locally, but running into the next problem, so will see if it is related or something else in my project setup that should be addressed in a different issue if at all.

**Comment by asgrim** [comment]
Fixed by #716
