### ISSUE TITLE
Custom `vendor-dir` not working in `Psr4Mapping`

### ISSUE THREAD

**Issue by tomasnorre** [Roave/BetterReflection#718]
I'm really sorry, that I'm not doing my homework good enough. I have found another issue with my change. Will try to have it don't fully this time. 

Sorry. 

**Affected:** 4.12.1 & 4.13.x

**Problem:** 

Even with the latest fix from 4.12.1 the custom vendor-dir isn't working, the `Psr4Mapping` is throwing an exception as it still thin that the folders should be found in `*/vendor/*`which isn't the case.

```shell
Provided path "Assert\" for prefix "/tmp/api-compare-06bfa8083aa22f6fdfe83de9807969b11f1e90c5_5fda50f9734d9/vendor/beberlei/assert/lib/Assert" is not a directory   
```
I have been able to verify this over tests, which I didn't add last time, otherwise I would have found this before merging.
Will grep through the repository for all `vendor` occurrences to "make sure" then are fixed this time. I'm really feeling bad about this.

Here is one of the problems:
https://github.com/Roave/BetterReflection/blob/9bfdcdd08da048c5522c7feed95bed85d3ef5254/src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php#L178

**Comment by Ocramius** [comment]
@tomasnorre no need to be sorry: you are on it, and all looked fine in the patch anyway :-)

It's actually super useful that you do this sort of analysis when opening new issues!

**Comment by Ocramius** [comment]
Handled in #719
