### ISSUE TITLE
Getting namespaces/classes in a file

### ISSUE THREAD

**Issue by aik099** [Roave/BetterReflection#732]
Hi,

I'm migrating from https://github.com/goaop/parser-reflection/ library and I'm interested in how do you do the `ReflectionFile` thing here. In that library it works like this:

1. create a `ReflectionFile` class instance on a specific file
2. call `getFileNamespaces` method to get instances of `ReflectionFileNamespace` class
3. then for each namespace object you can ask what's inside it, e.g. `getClasses` method will return array `ReflectionClass` class objects

I'm using that to scan a project with lots of PHP files placed around different places and I have no idea what's inside them (what class in what files or even multiple classes in a single file and a bunch of regular PHP code too).

Also how namespaces are handled (if there are several in a file)?

Thank you.

**Comment by asgrim** [comment]
You can fetch all the classes in a single file here: https://github.com/Roave/BetterReflection/blob/4.13.x/docs/usage.md#fetch-reflections-of-all-the-classes-in-a-file - if you need more control over how code is analysed, check out Source Locators: https://github.com/Roave/BetterReflection/blob/4.13.x/docs/usage.md#sourcelocators

We don't have the concept of fetching "all namespaces in a file" and then "all classes in that namespace" really. Each class reflection has information about its namespace however (as it would in internal PHP API).

**Comment by aik099** [comment]
@asgrim , would you be interested in a PR where such functionality is added?

**Comment by Ocramius** [comment]
I think https://github.com/Roave/BetterReflection/blob/89b3a0f3ee48a53b2907921bf5715db305329c62/docs/usage.md#fetch-reflections-of-all-the-classes-in-a-file is a sufficient solution to this:

 1. fetch all symbols in a file
 2. deduce the namespace for each symbol

This is transformation to be done in userland, not here: this library should rather focus on finding the symbols, not categorizing them.
