### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 36864 bytes) 

### ISSUE THREAD

**Issue by cmmer** [Roave/BetterReflection#747]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 36864 bytes) in vendor/roave/better-reflection/src/SourceLocator/Ast/Parser/MemoizingParser.php on line 47

What's going on

**Comment by asgrim** [comment]
You're running out of memory allowed by PHP. Better Reflection is quite memory intense, I'm afraid 128mb almost certainly isn't enough. You would need to increase PHP memory limit.

**Comment by Ocramius** [comment]
Closing here: @asgrim's comment pretty much explains it.
