### ISSUE TITLE
Don't ignore <MissingImmutableAnnotation errorLevel="suppress" /> by Psalm

### ISSUE THREAD

**Issue by kukulich** [Roave/BetterReflection#754]

**Comment by kukulich** [comment]
I hope this is "fixed" by https://github.com/Roave/BetterReflection/commit/9fde8ea0f764391172906cc1d9c86a229bacbf2f

I'm not sure it can be done better in adapters.

**Comment by Ocramius** [comment]
I think this is a good enough solution for now: downstream consumers of adapters rely on `\Reflection*` symbols anyway, so they will detect immutability accordingly.

Our code does not mutate symbols (and the little bit of what's left in code mutation should probably be moved out, at some point)
