### ISSUE TITLE
Implement adapters for `ReflectionAttribute`, `ReflectionEnumPureCase`, `ReflectionEnumBackedCase` and `ReflectionEnumUnitcase` when supported by PHP

### ISSUE THREAD

**Issue by Ocramius** [Roave/BetterReflection#789]
Ref: https://bugs.php.net/bug.php?id=81474

**Comment by sasezaki** [comment]
currently, no longer non-final at PHP 8.1 .
For 8.0, today I requested make ReflectionAttribute non-final at https://github.com/php/php-src/pull/7545 .

**Comment by kukulich** [comment]
Ok, `ReflectionAttribute` in 8.0.12 should not be final 👍

**Comment by Ocramius** [comment]
So I suppose we need to use `^8.0.12` as dependency then :-)

**Comment by kukulich** [comment]
Yes, waiting for the release :)
