### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by kukulich** [Roave/BetterReflection#806]
- [x] Green build https://github.com/Roave/BetterReflection/pull/767
- [x] Readonly properties https://github.com/Roave/BetterReflection/pull/811
- [x] Final constants https://github.com/Roave/BetterReflection/pull/814
- [x] `never` type https://github.com/Roave/BetterReflection/pull/812
- [x] `ReflectionClass::isEnum()` and `ReflectionObject::isEnum()` https://github.com/Roave/BetterReflection/pull/813
- [x] `ReflectionFunction::isStatic()` https://github.com/Roave/BetterReflection/pull/815
- [x] ~~`getClosureUsedVariables()`~~
- [x] Intersection types https://github.com/Roave/BetterReflection/pull/818
- [x] Tentative return types https://github.com/Roave/BetterReflection/pull/817
- [x] New in initializers https://github.com/Roave/BetterReflection/pull/819
- [x] Enums https://github.com/Roave/BetterReflection/pull/827

**Comment by Ocramius** [comment]
I'm gonna clean up the remaining tasks and will try this out ASAP on `roave/backward-compatibility-check`: we're really close! \o/
