### ISSUE TITLE
Automerge Dependebot PR

### ISSUE THREAD

**Issue by kukulich** [Roave/BetterReflection#865]
Current solution does not work so we can try something else:

1. We can use only one workflow
It works in https://github.com/Roave/BackwardCompatibilityCheck/

2. We can try https://github.com/WyriHaximus/github-action-wait-for-status
It works in https://github.com/phpstan/phpstan-src/blob/master/.github/workflows/merge-bot-pr.yml

3. Or we can try something with GitHub "Auto merge" functionality, eg. https://github.com/marketplace/actions/dependabot-auto-merge or https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request

**Comment by asgrim** [comment]
@kukulich I rolled this one out to another project: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request

See: https://github.com/browscap/browscap-site/blob/master/.github/workflows/automatic-merge-browscap-updates.yml
I haven't done a full end to end release yet but it looks like it might be used

**Comment by kukulich** [comment]
@asgrim Does it need the "Auto merge" feature enabled?

**Comment by asgrim** [comment]
Yes

**Comment by kukulich** [comment]
@asgrim I'll send PR for the option you and @Ocramius choose 😄

**Comment by Ocramius** [comment]
Careful about auto-merge usage: it kinda breaks when approval is given, yet some comments still need polishing

**Comment by asgrim** [comment]
> Careful about auto-merge usage: it kinda breaks when approval is given, yet some comments still need polishing

You can prevent auto merge from merging if comments are not resolved, would that suffice?

![Screenshot_20211121-071839.png](https://user-images.githubusercontent.com/496145/142753369-5a1001b2-7f64-49e0-859a-e70d80114a98.png)

The settings for the "branch protection rules" are what govern when the "Auto merge" feature merges, when enabled for a PR. We'd need to configure this properly too.

**Comment by kukulich** [comment]
Implemented in https://github.com/Roave/BetterReflection/pull/867
