### ISSUE TITLE
Exploring `ReflectionMethod::isConstructor()`

### ISSUE THREAD

**Issue by WinterSilence** [Roave/BetterReflection#930]
https://github.com/Roave/BetterReflection/blob/9da142a1eaa31fc9467abd971ed05a29a5ac8a30/src/Reflection/ReflectionMethod.php#L268

why method check namespace to detect class constructor?

**Comment by Ocramius** [comment]
PHP 4 ctors only apply to non-namespaced code

**Comment by WinterSilence** [comment]
@Ocramius we support php4?!

**Comment by WinterSilence** [comment]
@Ocramius again used declaring class instead current
https://github.com/Roave/BetterReflection/blob/9da142a1eaa31fc9467abd971ed05a29a5ac8a30/src/Reflection/ReflectionMethod.php#L267
it's error:
class `Foo` declare constructor `bar();`, class `Bar` extends `Foo`, `Bar::bar()` - deprecated constructor

**Comment by Ocramius** [comment]
See https://github.com/Roave/BetterReflection/pull/907

See https://github.com/ondrejmirtes/BetterReflection/commit/6f597e60df0946c1b4f6fa935b352e04f9ce9642

**Comment by WinterSilence** [comment]
@Ocramius i'm understand you
> class Foo declare constructor `bar()`, class Bar extends Foo, Bar::bar() - deprecated constructor

you understand me?
~~~php
class Foo {
     public function bar() {
     }
}
class Bar extends Foo {
}
~~~
`ReflectionMethod::createFromName(Bar::class, 'bar')->isConstructor();` return false

**Comment by Ocramius** [comment]
Not really: please write a test case

**Comment by WinterSilence** [comment]
@Ocramius failing test https://github.com/Roave/BetterReflection/pull/933/files
