### ISSUE TITLE
ReflectionNamedType::isBuiltIn incorrect behavior 

### ISSUE THREAD

**Issue by aurimasniekis** [Roave/BetterReflection#961]
I have noticed that [`ReflectionNamedType::isBuiltIn`](https://github.com/Roave/BetterReflection/blob/5.1.x/src/Reflection/ReflectionNamedType.php#L60) is working incorrectly, and it looks like it was broken after #750 merged.

Neither `self`, `parent`, `static` is built-in types in PHP according original PHP Reflections.

The last commit I can find which looked like it worked like should be this 3419b0f28b6d80f1af6bece384a125e5350bbb3d [`ReflectionNamedType::isBuiltIn`](https://github.com/Roave/BetterReflection/blob/3419b0f28b6d80f1af6bece384a125e5350bbb3d/src/Reflection/Adapter/ReflectionNamedType.php#L43)

I am not sure if removing them from the list is a good thing because I think those are used somewhere else. I also think maybe having a test to test the list of types against real Reflection to see if it's really is a built-in type would be nice to prevent this in the future.

**Comment by aurimasniekis** [comment]
Here is proof https://3v4l.org/JXSes#v8.1.1

**Comment by kukulich** [comment]
@Ocramius `self`, `parent`, `static` were not built-in only in adapter in previous version. I would like to fix it again in this way - BR will report them as build-in and adapter as not build-in.

**Comment by Ocramius** [comment]
Yeah, adapter-only seems okay 👍

**Comment by aurimasniekis** [comment]
Wouldnt this make this Compatibility mark not accurate?

https://github.com/Roave/BetterReflection/blob/5.1.x/docs/compatibility.md?plain=1#L174

**Comment by aurimasniekis** [comment]
I am not against it, just that it's really widely used common logic such as:

```php
if (! $type->isBuiltin() && $name === 'static') {
  // ...
}

if (! $type->isBuiltin() && $name === 'self') {
  // ...
}

if (! $type->isBuiltin() && $name === 'parent') {
  // ...
}
```

**Comment by Ocramius** [comment]
Handled in #962
