### ISSUE TITLE
`ReflectionFunctionAbstract` has incorrect `locatedSource` value

### ISSUE THREAD

**Issue by aurimasniekis** [Roave/BetterReflection#964]
When trying to get the location of the method which is inherited from the parent class fails with the `InvalidNodePosition` exception, but from a deeper look, it seems that the `$this->locatedSource->getSource()` method returns not the parent class source but the source of which implemented it.

From looking around the code seems, like it should return `$this->getDeclaringClass()->getLocatedSource()->getSource()` for `ReflectionMethod` and `$this->locatedSource->getSource()`  for `ReflectionFunction`

Reproducible code:
<details>
  <summary>Click to expand!</summary>

```php
<?php

declare(strict_types=1);

use Roave\BetterReflection\Reflection\ReflectionClass;
use Roave\BetterReflection\Reflection\ReflectionEnum;

require_once __DIR__ . '/vendor/autoload.php';

$classRef = ReflectionClass::createFromName(ReflectionEnum::class);
$methodRef = $classRef->getMethod('__toString');
$methodRef->getStartColumn();
```

</details>

**Comment by Ocramius** [comment]
Handled in #965

**Comment by aurimasniekis** [comment]
Thanks! @Ocramius @kukulich
