### ISSUE TITLE
Find a way to decrease complexity of compileBinaryOperator method

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#98]
https://github.com/Roave/BetterReflection/pull/95/files#diff-c3ee776df4185cfa0fffb53df92d78c3R126

It's a massive block simply full of `if`s... meaning complexity of this method is very large.

Could use strategy pattern to reduce this perhaps?

**Comment by tomzx** [comment]
@asgrim Would you rather implement this as a set of new classes or a set of new methods in the current class? (`$this->compileBinaryOperator{$operation}($node, $context);` with `$operation` being the binary operator class name).

**Comment by asgrim** [comment]
A set of small specific classes is probably tidier & improves testability IMO; as long as the naming is reasonable and performance doesn't degrade significantly (this lib isn't built for speed, but let's not make it too terrible!) :)

**Comment by Ocramius** [comment]
Handled in https://github.com/Roave/BetterReflection/pull/352
