### ISSUE TITLE
6.0 cleanup

### ISSUE THREAD

**Issue by kukulich** [Roave/BetterReflection#981]
- [x] Remove `Roave\BetterReflection\Util\Autoload` https://github.com/Roave/BetterReflection/pull/1142
- [x] Make `ReflectionEnum::__construct()` private https://github.com/Roave/BetterReflection/pull/1139
- [x] Remove `ReflectionType::__construct()` and `ReflectionType::getOwner()` https://github.com/Roave/BetterReflection/pull/1140
- [x] Remove adapter `ReflectionProperty::isAccessible()` https://github.com/Roave/BetterReflection/pull/1141

**Comment by Ocramius** [comment]
@kukulich btw, milestone + issues > checklists :D

**Comment by Ocramius** [comment]
Awesome work, @kukulich! :tada:
